/* Données de cours de Psyché : six documents du M2 PSP (EHESP, 2026-2027). */
const FICHES_URL="./fiches.html";
const UNITS=[
/* ================= HÉMON : CRÉDIBILITÉ ET MÉSINFORMATION ================= */
{id:"u1",n:1,c:"--u1",title:"Littératie et mésinformation en santé",who:"Brivael Hémon · jugements de crédibilité",lessons:[
{id:"u1l1",title:"Dés-, més- ou malinformation ?",q:[
{t:"qcm",q:"Selon Sørensen et al. (2015), la littératie en santé, c'est…",o:["la connaissance, les compétences, la motivation et la capacité à repérer, comprendre, évaluer et utiliser des informations sur la santé pour décider","le niveau de diplôme d'une personne dans les professions de santé","la capacité à lire une ordonnance","le nombre de sources d'information consultées par une personne"],a:0,e:"Quatre verbes à retenir : repérer, comprendre, évaluer, utiliser, dans les soins, la prévention et la promotion de la santé."},
{t:"assoc",q:"Associe chaque notion à sa définition.",p:[["Désinformation","information erronée diffusée avec une intention (lucrative, politique…)"],["Mésinformation","information erronée sans intention malveillante, « erreur honnête »"],["Malinformation","information correcte mais trompeuse ou utilisée pour nuire"]],e:"Le critère qui sépare désinformation et mésinformation, c'est l'intention."},
{t:"vf",q:"La mésinformation suppose une intention de tromper.",a:false,e:"Non : la mésinformation est une « erreur honnête ». L'intention caractérise la désinformation."},
{t:"qcm",q:"Publier des données confidentielles pour nuire à quelqu'un relève de…",o:["la malinformation","la mésinformation","la désinformation au sens strict","la littératie numérique"],a:0,e:"Malinformation : l'information est correcte, mais elle sert à nuire (ou elle trompe par cherry picking ou mise hors contexte)."},
{t:"trou",q:"Choisir seulement les données qui arrangent (« ___ ») transforme une information correcte en malinformation.",o:["cherry picking","prebunking","debunking","nudge"],a:0,e:"Le cherry picking et la mise hors contexte rendent trompeuse une information pourtant correcte."},
{t:"qcm",q:"Lequel de ces thèmes N'EST PAS cité par Molimard et al. (2026) parmi les thèmes majeurs de mésinformation ?",o:["La sécurité routière","Les vaccins","La santé mentale","La santé des femmes"],a:0,e:"Thèmes cités : pratiques de soins non conventionnelles, vaccins, alimentation, traitements non validés ou détournés, santé mentale, santé des femmes, risques environnementaux et climat."},
{t:"vf",q:"Le rapport Molimard et al. (2026) a été remis au ministre de la Santé et propose une stratégie nationale contre la désinformation en santé.",a:true,e:"Information en santé : bilan des forces et des faiblesses, recommandations pour une stratégie nationale d'information et de lutte contre la désinformation."}]},
{id:"u1l2",title:"Risques et fragilités",q:[
{t:"qcm",q:"Quel risque de la mésinformation en santé est cité dans le cours ?",o:["L'interruption de traitements et la perte de chance","La baisse du prix des médicaments","La surcharge des lignes d'écoute","La hausse du nombre de médecins"],a:0,e:"Risques cités : errance diagnostique et thérapeutique, interruption de traitement et perte de chance, payer pour des méthodes inefficaces, résurgence de maladies évitables."},
{t:"vf",q:"La résurgence de maladies évitables fait partie des risques de la mésinformation en santé.",a:true,e:"Par exemple quand la défiance envers les vaccins fait reculer la couverture vaccinale."},
{t:"qcm",q:"Quelles sont les trois fragilités relevées par Molimard et al. (2026) ?",o:["Littératie en santé et scientifique insuffisante, méconnaissance des méthodes scientifiques, science vue comme des certitudes figées","Manque de médecins, manque de lits, manque de moyens","Trop d'écrans, trop de publicité, trop de réseaux","Pauvreté, isolement, chômage"],a:0,e:"Les trois fragilités touchent la littératie, la connaissance des méthodes et la conception de la science."},
{t:"vf",q:"Pour Molimard et al., concevoir la science comme un ensemble de certitudes figées est une fragilité face à la désinformation.",a:true,e:"Si l'on attend des certitudes, un changement de recommandation paraît suspect."},
{t:"qcm",q:"Selon le cours, pourquoi le rapport à l'information est-il « bouleversé par le numérique » ?",o:["Plateformes sans gestion éditoriale, rôle des algorithmes, IA générative pour créer du contenu ou obtenir des réponses","Parce que les journaux papier ont disparu","Parce qu'Internet est réservé aux jeunes","Parce que les sites officiels sont payants"],a:0,e:"Tout le monde peut publier, les algorithmes trient, et l'IA générative produit ou répond directement."},
{t:"trou",q:"Sur les plateformes sans gestion ___, tout le monde peut publier.",o:["éditoriale","financière","médicale","juridique"],a:0,e:"L'absence de filtre éditorial fait partie du bouleversement numérique décrit par Molimard et al."},
{t:"qcm",q:"Selon les objectifs de la séance, que faut-il savoir faire ?",o:["Identifier les thèmes de mésinformation, analyser les stratégies de jugement de crédibilité, comprendre les heuristiques, connaître l'efficacité et les limites des interventions","Créer un site de fact-checking","Calculer un alpha de Cronbach","Rédiger un projet territorial de santé mentale"],a:0,e:"Quatre objectifs pédagogiques, repris dans les « points à retenir pour l'examen »."}]}
]},
{id:"u2",n:2,c:"--u2",title:"Juger la crédibilité",who:"Brivael Hémon · stratégies et heuristiques",lessons:[
{id:"u2l1",title:"Stratégies d'évaluation",q:[
{t:"qcm",q:"Dans le modèle de Barzilai et al. (2020), l'évaluation indirecte porte sur…",o:["la crédibilité de la source","la cohérence avec mes connaissances","le discours du document","la corroboration entre documents"],a:0,e:"Évaluation directe : validité et qualité de l'information. Évaluation indirecte : crédibilité de la source."},
{t:"assoc",q:"Associe chaque stratégie de Barzilai et al. (2020) à son principe.",p:[["Validation basée sur les connaissances","comparer l'information à ce que je sais déjà"],["Évaluation basée sur le discours","examiner la manière dont le message argumente"],["Corroboration","vérifier si d'autres documents disent la même chose"],["Évaluation de la source","juger qui parle et sa crédibilité"]],e:"Les trois premières sont des stratégies d'évaluation directe ; la quatrième est l'évaluation indirecte."},
{t:"vf",q:"La corroboration fait partie de l'évaluation directe des informations dans le schéma de Barzilai et al.",a:true,e:"Elle porte sur la validité de l'information elle-même, en la croisant avec d'autres documents."},
{t:"qcm",q:"Dans le modèle adapté de Geay (2023), la crédibilité d'une source repose sur deux piliers. Lesquels ?",o:["La compétence et la confiance","La popularité et la rapidité","Le diplôme et l'âge","Le nombre de likes et le design"],a:0,e:"Compétence : est-elle capable de dire le vrai ? Confiance : a-t-elle l'intention de me dire le vrai ?"},
{t:"assoc",q:"Associe chaque critère du modèle de Geay (2023) à la question qu'il pose.",p:[["Expertise","a-t-elle les connaissances pratiques et théoriques nécessaires ?"],["Réputation","est-elle reconnue pour dire le vrai ?"],["Vigilance","fait-elle l'effort de communiquer des infos utiles et intelligibles ?"]],e:"Expertise (théorie, expérience) et réputation (autorité, popularité) relèvent de la compétence ; la vigilance (intérêt, engagement) relève de la confiance."},
{t:"qcm",q:"Chez Geay (2023), la vigilance d'une source se rattache à…",o:["la confiance : a-t-elle l'intention de me dire le vrai ?","la compétence : est-elle capable de dire le vrai ?","l'expertise théorique","la popularité"],a:0,e:"La vigilance (intérêt, engagement) est du côté de la confiance."},
{t:"trou",q:"La réputation d'une source s'appuie sur son autorité et sa ___.",o:["popularité","vigilance","expérience","intention"],a:0,e:"Réputation = autorité + popularité. Expertise = théorie + expérience."}]},
{id:"u2l2",title:"Ce que l'on fait vraiment",q:[
{t:"qcm",q:"Quand on manque de connaissances pointues sur un sujet socio-scientifique, quelle tendance observe-t-on ?",o:["Une tendance à l'évaluation directe, à partir de ses connaissances et croyances, au détriment de l'évaluation de la source","Une évaluation systématique de l'expertise de la source","Le refus de juger","Le recours automatique à la corroboration"],a:0,e:"C'est pourtant dans ce cas qu'évaluer la source serait le plus utile."},
{t:"qcm",q:"Chez les adolescent·es (Abed & Barzilai, 2023), quels critères sont les plus souvent mentionnés pour juger des vidéos sur le climat ?",o:["Les critères communicatifs (qualité visuelle, expérience utilisateur) et la qualité des explications","La validité des informations","L'expertise de la source","Les conflits d'intérêts"],a:0,e:"La validité des infos et l'expertise de la source sont parmi les critères les MOINS mentionnés."},
{t:"vf",q:"Dès l'adolescence, on dispose de compétences pour identifier et juger la crédibilité d'une source (Potocki et al., 2020).",a:true,e:"Les compétences existent ; c'est leur mobilisation qui fait défaut."},
{t:"qcm",q:"Quelle conclusion le cours tire-t-il des travaux de Potocki (2020) et Hémon (2025) ?",o:["Ce n'est pas juste un manque de compétences, mais aussi de motivation ou de dispositions","Les adolescents ne savent pas évaluer une source","L'âge ne change rien au discernement","Il suffit de donner une consigne une fois"],a:0,e:"On a conscience de l'importance de la source mais on s'engage peu dans son évaluation sans consigne explicite ou sans intérêt pour le sujet."},
{t:"vf",q:"La capacité à discerner une source compétente d'une source peu compétente évolue avec l'âge (Hémon et al., 2025).",a:true,e:"Étude chez des collégiens et lycéens, avec des vidéos où variait le niveau d'expertise de la source."},
{t:"qcm",q:"Laquelle de ces stratégies est citée dans le brainstorming du cours pour évaluer un document ?",o:["Regarder qui partage l'information, par exemple s'il est concerné","Compter le nombre de mots","Préférer la vidéo la plus longue","Vérifier la date de naissance de l'auteur"],a:0,e:"Autres stratégies citées : corroboration, vocabulaire utilisé (par ex. « médecine douce »)."},
{t:"assoc",q:"Classe ces critères du brainstorming : portent-ils sur l'info ou sur la source ?",p:[["Cohérence avec mes croyances","crédibilité de l'information"],["Qualité de la méthode","crédibilité de l'information"],["Conflit d'intérêts","crédibilité de la source"],["Expertise sur le sujet","crédibilité de la source"]],e:"Réputation, autorité, expertise, conflit d'intérêts et usage de l'IA concernent la source."}]},
{id:"u2l3",title:"Heuristiques et biais",q:[
{t:"qcm",q:"Selon Gigerenzer & Gaissmaier (2011), une heuristique est…",o:["une stratégie qui ignore une partie de l'information pour décider plus vite, de façon plus économique et/ou efficace","une erreur de raisonnement systématique","un raisonnement lent et analytique","une règle juridique"],a:0,e:"L'heuristique est généralement utile et efficace ; c'est un raccourci, pas forcément une erreur."},
{t:"trou",q:"Le principe de ___ (Chaiken & Trope, 1999) : équilibre entre effort cognitif minimal et résultat suffisamment satisfaisant.",o:["suffisance","précaution","symétrie","corroboration"],a:0,e:"On s'arrête quand le résultat est « assez bon » pour l'effort fourni."},
{t:"vf",q:"Une heuristique est généralement utile et efficace.",a:true,e:"Elle devient un biais quand elle mène à une décision non adaptée ou incorrecte d'un point de vue normatif."},
{t:"qcm",q:"Qu'est-ce qu'un biais cognitif selon le cours ?",o:["Le résultat de l'usage d'une heuristique menant à une décision non adaptée ou incorrecte d'un point de vue normatif","Une erreur aléatoire","Un manque de compétence","Un trouble psychique"],a:0,e:"Le biais dévie systématiquement dans la même direction ; ce n'est ni une erreur aléatoire ni un manque de compétence."},
{t:"assoc",q:"Associe chaque système de pensée à ses caractéristiques.",p:[["Système 1","intuitif, rapide, automatique, peu d'effort"],["Système 2","analytique, lent, conscient, coûteux cognitivement"]],e:"Travaux de Kahneman et Tversky sur les deux systèmes de pensée (Evans, 2008)."},
{t:"qcm",q:"Dans quelles conditions le risque d'erreur d'un biais augmente-t-il ?",o:["Sous pression temporelle ou forte charge cognitive","Quand on dort bien","Quand on lit un texte court","Quand on est expert du sujet"],a:0,e:"Pression temporelle et charge cognitive poussent vers le système 1."},
{t:"qcm",q:"« Si tu dépasses la personne à la seconde place, à quelle place te retrouves-tu ? » Quelle est la bonne réponse de cet item de réflexion cognitive ?",o:["Deuxième","Première","Troisième","Ça dépend du nombre de coureurs"],a:0,e:"Le système 1 souffle « premier » ; en réalité on prend sa place : deuxième. Items de Frederick (2005)."},
{t:"qcm",q:"Des nénuphars doublent chaque jour et couvrent tout le lac en 48 jours. En combien de jours en couvrent-ils la moitié ?",o:["47 jours","24 jours","12 jours","46 jours"],a:0,e:"La veille du dernier jour : 47. La réponse intuitive « 24 » est le piège du système 1."},
{t:"qcm",q:"Trois injections espacées de trois semaines : combien de temps faut-il pour les faire toutes ?",o:["Six semaines","Neuf semaines","Trois semaines","Douze semaines"],a:0,e:"Deux intervalles de trois semaines entre trois injections : six semaines."}]},
{id:"u2l4",title:"Quatre heuristiques de crédibilité",q:[
{t:"assoc",q:"Associe chaque heuristique (Metzger & Flanagin, 2013) à sa définition.",p:[["Confirmation","juger crédible ce qui est cohérent avec nos croyances"],["Réputation","juger crédible parce que la source est connue ou prestigieuse"],["Non-respect des attentes","juger non crédible un message qui ne correspond pas à nos attentes (mauvais design…)"],["Approbation","se fier à l'opinion d'autrui (proches, likes, commentaires)"]],e:"Quatre heuristiques au programme de l'examen : sache les définir et donner un exemple."},
{t:"qcm",q:"Un médecin très connu s'exprime sur un sujet hors de sa spécialité et on le croit. Quelle heuristique ?",o:["Réputation","Approbation","Confirmation","Non-respect des attentes"],a:0,e:"Le risque de l'heuristique de réputation : croire un émetteur connu même hors de son champ de compétence."},
{t:"qcm",q:"« Ce post a 50 000 likes, c'est sûrement vrai. » Quelle heuristique ?",o:["Approbation","Réputation","Confirmation","Suffisance"],a:0,e:"L'heuristique d'approbation s'appuie sur l'opinion d'autrui, y compris le nombre de likes."},
{t:"qcm",q:"On écarte un article fiable parce que son site a l'air amateur. Quelle heuristique ?",o:["Non-respect des attentes","Confirmation","Approbation","Réputation"],a:0,e:"Mauvais design, manque de professionnalisme : le message ne correspond pas à nos attentes. L'inverse joue aussi."},
{t:"vf",q:"L'heuristique de confirmation conduit aussi à négliger ou rejeter les informations qui infirment nos croyances.",a:true,e:"Rechercher, retenir et juger crédible ce qui confirme ; négliger ou rejeter ce qui infirme."},
{t:"vf",q:"L'heuristique de non-respect des attentes ne joue que dans un sens : elle fait juger non crédible.",a:false,e:"Le cours précise « et inversement » : un message très professionnel peut être jugé crédible pour cette seule raison."},
{t:"trou",q:"L'heuristique d'___ consiste à juger la crédibilité d'après l'opinion des autres.",o:["approbation","réputation","autorité","expertise"],a:0,e:"Personne que l'on connaît ou apprécie, nombre de likes, nature des commentaires."}]}
]},
{id:"u3",n:3,c:"--u3",title:"Croyances erronées et interventions",who:"Brivael Hémon · Ecker 2022, Kozyreva 2024",lessons:[
{id:"u3l1",title:"Pourquoi on y croit",q:[
{t:"qcm",q:"Le modèle du déficit d'information affirme que…",o:["les gens adhèrent aux fausses informations par manque de connaissances, et qu'il suffirait de bien expliquer","les gens croient ce qui flatte leurs émotions","les fausses informations viennent des algorithmes","la mésinformation est toujours intentionnelle"],a:0,e:"Le cours le juge insuffisant : il fait l'impasse sur les processus cognitifs, sociaux et affectifs."},
{t:"vf",q:"Selon le cours, bien expliquer suffit pour que les personnes changent leurs croyances erronées.",a:false,e:"C'est le modèle du déficit d'information, jugé insuffisant."},
{t:"assoc",q:"Range ces moteurs des croyances erronées (Ecker et al., 2022) dans leur famille.",p:[["Pensée intuitive","facteurs cognitifs"],["Vérité illusoire","facteurs cognitifs"],["Émotions","facteurs socio-affectifs"],["Vision du monde","facteurs socio-affectifs"]],e:"Cognitifs : pensée intuitive, biais cognitifs, vérité illusoire. Socio-affectifs : caractéristiques de la source, émotions, vision du monde."},
{t:"qcm",q:"Dans le modèle d'Ecker et al. (2022), les caractéristiques de la source sont un facteur…",o:["socio-affectif","cognitif","économique","biologique"],a:0,e:"Source, émotions et vision du monde sont les facteurs socio-affectifs."},
{t:"qcm",q:"L'effet de vérité illusoire désigne…",o:["le fait qu'une information répétée, devenue familière, paraisse plus vraie","le fait de croire ce que disent les experts","l'illusion d'avoir tout compris","le rejet des informations nouvelles"],a:0,e:"D'où la consigne du debunking : ne citer le mythe qu'une seule fois."},
{t:"vf",q:"Les biais cognitifs font partie des facteurs cognitifs de l'adhésion aux croyances erronées.",a:true,e:"Avec la pensée intuitive et la vérité illusoire."}]},
{id:"u3l2",title:"La boîte à outils",q:[
{t:"qcm",q:"Qu'est-ce qu'un nudge selon le cours ?",o:["Une conception qui incite à une décision bénéfique, sans contrainte, en utilisant des processus du fonctionnement humain","Une sanction contre les désinformateurs","Un cours d'éducation aux médias","Un message qui contredit une fausse information précise"],a:0,e:"Coup de pouce : pas de contrainte, on s'appuie sur le fonctionnement humain."},
{t:"assoc",q:"Associe chaque nudge à son principe.",p:[["Incitation à l'exactitude","demander d'évaluer la fiabilité d'un post avant de le partager"],["Friction","rendre le partage plus difficile, ajouter des clics"],["Normes sociales","mobiliser ce qui se fait ou ce qui doit se faire"]],e:"Trois nudges de Kozyreva et al. (2024)."},
{t:"assoc",q:"Range chaque outil dans sa famille (Kozyreva et al., 2024).",p:[["Friction","nudges"],["Lecture latérale","interventions éducatives"],["Notes de communauté","réfutations"],["Inoculation","interventions éducatives"]],e:"Nudges : exactitude, friction, normes. Éducatives : littératie des médias, inoculation. Réfutations : labels, scores de crédibilité, debunking."},
{t:"qcm",q:"Les interventions éducatives visent à…",o:["aider au développement de compétences","contraindre les plateformes","punir les auteurs","rendre le partage plus lent"],a:0,e:"Éducation à la littératie des médias (lecture latérale, critères de crédibilité) et inoculation."},
{t:"qcm",q:"Un score de confiance attribué aux sources par des professionnels, « sur le modèle du nutriscore », est…",o:["une réfutation : score de crédibilité des sources","un nudge de friction","une inoculation","une norme sociale"],a:0,e:"Les réfutations expliquent pourquoi une information est erronée : labels, scores de crédibilité, debunking."},
{t:"vf",q:"Les « notes de communauté » des réseaux sociaux sont un exemple de label sur la fiabilité d'un contenu.",a:true,e:"Elles affichent qu'une info est fausse ou trompeuse : c'est une réfutation."},
{t:"trou",q:"La ___ (prebunking) expose aux méthodes de désinformation pour développer des compétences de détection.",o:["inoculation","friction","corroboration","réputation"],a:0,e:"L'inoculation est classée parmi les interventions éducatives."}]},
{id:"u3l3",title:"Prebunking et debunking",q:[
{t:"qcm",q:"Sur quelle métaphore repose l'inoculation ?",o:["La métaphore vaccinale : exposer à une forme affaiblie pour être « protégé » plus tard","La métaphore du filtre","La métaphore de l'iceberg","La métaphore du ballon"],a:0,e:"On expose à une info erronée ou à une technique (faux experts, argumentation fallacieuse) pour mieux la reconnaître ensuite."},
{t:"qcm",q:"Que contient une inoculation ?",o:["Une alerte sur une tentative de désinformation à venir et une réfutation anticipée des arguments ou techniques","Une sanction et une amende","Un score de crédibilité","Une friction au partage"],a:0,e:"Alerte + réfutation anticipée."},
{t:"vf",q:"Les effets de l'inoculation durent plusieurs années sans rappel.",a:false,e:"Quelques semaines à quelques mois ; des « rappels » peuvent prolonger la durée."},
{t:"vf",q:"L'inoculation peut prendre une forme active, comme un jeu.",a:true,e:"Message passif (article, vidéo) ou forme active (gamification), par ex. les jeux d'inoculation.science comme Bad Vaxx."},
{t:"qcm",q:"Quel avantage de l'inoculation est souligné par rapport au debunking ?",o:["Elle développe des compétences de détection même si le contenu de la désinformation change","Elle est toujours définitive","Elle ne demande aucune source crédible","Elle répète l'information fausse plusieurs fois"],a:0,e:"Elle vise la technique, pas seulement un mythe précis."},
{t:"ordre",q:"Remets dans l'ordre la structure d'un debunking (Ecker et al., 2022).",items:["Fait : donner l'explication correcte","Mythe : le signaler comme faux, une seule fois","Erreur : expliquer la technique fallacieuse du mythe","Fait : répéter l'information correcte"],e:"Fait → mythe avec avertissement → technique fallacieuse → fait répété."},
{t:"qcm",q:"Pourquoi ne citer l'information erronée qu'une seule fois dans un debunking ?",o:["Pour éviter de renforcer sa familiarité (effet de vérité illusoire)","Pour gagner de la place","Parce que c'est interdit par la loi","Pour éviter un conflit d'intérêts"],a:0,e:"La répétition rend le mythe familier, donc plus crédible."},
{t:"qcm",q:"Laquelle N'EST PAS une recommandation du cours pour un debunking efficace ?",o:["Ridiculiser les personnes qui y croient pour marquer les esprits","Donner une explication au phénomène, pas seulement démentir","Passer par une source reconnue comme crédible","Terminer en répétant l'information correcte"],a:0,e:"Il faut au contraire un langage empathique, simple, sans position dominante."},
{t:"vf",q:"Selon le cours, se contenter de démentir suffit : il n'est pas utile d'expliquer le phénomène.",a:false,e:"Il faut donner une explication, qui répond au besoin de certitude."}]},
{id:"u3l4",title:"Limites et approche systémique",q:[
{t:"assoc",q:"Associe chaque limite des interventions à son explication.",p:[["Évaluation","surtout testées en laboratoire, peu en situation réelle"],["Durée","effets difficiles à tenir dans le temps"],["Cibles","ceux qui s'y exposent ne sont pas ceux qui en ont le plus besoin"],["Propagation","la mésinformation coûte moins cher à produire"]],e:"Quatre limites générales, à citer dans le dossier de groupe."},
{t:"vf",q:"La mésinformation est plus facile et moins coûteuse à produire que les interventions éducatives ou de réfutation.",a:true,e:"C'est la limite de la « propagation »."},
{t:"qcm",q:"Que recommande le cours face aux limites des interventions individuelles ?",o:["Les combiner avec des interventions plus larges : littératie à l'école, confiance dans la science, régulation des plateformes, sanctions","Les abandonner","Ne cibler que les jeunes","Remplacer tout par du debunking"],a:0,e:"Approche systémique (Altay, 2026 ; Ecker et al., 2022)."},
{t:"qcm",q:"Quel facteur est cité dans l'approche systémique comme lié à l'adhésion aux croyances conspirationnistes ?",o:["Les inégalités, la précarité et la corruption","La météo","Le niveau sportif","La taille des villes"],a:0,e:"Rôle des inégalités, de la précarité et de la corruption."},
{t:"qcm",q:"Pour durer, que faut-il faire selon le cours ?",o:["Répéter les interventions en diversifiant les formats","Faire une seule intervention très forte","Ne jamais répéter","Ne cibler que les experts"],a:0,e:"Des effets bénéfiques mais difficiles à tenir : répéter, varier les formats."},
{t:"qcm",q:"Le travail de groupe demande un document de synthèse de quelle longueur ?",o:["1 à 2 pages","10 pages","Un poster A0","Une vidéo de 3 minutes"],a:0,e:"Groupes d'environ 4 : concevoir un prebunking ou un debunking, synthèse de 1 à 2 pages."},
{t:"qcm",q:"Lequel de ces éléments N'EST PAS demandé dans la synthèse du travail de groupe ?",o:["Le budget détaillé de l'intervention","Le public cible et pourquoi il adhère à l'info","La stratégie d'évaluation de l'efficacité","Les limites anticipées"],a:0,e:"Demandés : thématique et risque de santé publique, public cible, méthode, prototype de message, canal et source, évaluation, limites."}]}
]},
/* ================= MOREAU : PROMOTION ET PRÉVENTION ================= */
{id:"u4",n:4,c:"--u4",title:"Santé mentale : notions et chiffres",who:"Delphine Moreau · promotion et prévention",lessons:[
{id:"u4l1",title:"Trois dimensions",q:[
{t:"qcm",q:"Quelles sont les trois dimensions généralement incluses dans la notion de santé mentale ?",o:["Santé mentale positive, détresse psychologique, troubles psychiatriques","Enfance, adolescence, âge adulte","Prévention, soin, réinsertion","Biologique, psychologique, social"],a:0,e:"Santé mentale positive (bien-être), détresse ou « mal-être », troubles psychiatriques."},
{t:"assoc",q:"Associe chaque dimension à sa description.",p:[["Santé mentale positive","un état de bien-être mental (définition OMS)"],["Détresse psychologique","symptômes dépressifs ou anxieux passagers et de moindre intensité"],["Troubles psychiatriques","passagers ou durables, plus ou moins sévères"]],e:"La notion de santé mentale est large."},
{t:"vf",q:"Selon l'OMS, la santé mentale est davantage que l'absence de troubles ou de handicaps mentaux.",a:true,e:"Corollaire de la définition de la santé de 1948 : un état de complet bien-être, pas seulement l'absence de maladie."},
{t:"qcm",q:"Selon l'OMS, la santé mentale est un état de bien-être qui permet notamment…",o:["de faire face aux sources de stress, de réaliser son potentiel, de bien apprendre et travailler, de contribuer à la communauté","de ne jamais ressentir de tristesse","d'éviter tout contact avec la psychiatrie","d'avoir un diagnostic posé"],a:0,e:"Elle a une valeur en soi et fait partie intégrante de notre bien-être."},
{t:"qcm",q:"Le modèle présenté par Aude Caria (Psycom, 2019) croise deux axes. Lesquels ?",o:["Santé mentale (optimale à minimale) et maladie mentale (état maximal à minimal)","Âge et sexe","Revenu et diplôme","Soin libre et soin contraint"],a:0,e:"Deux continuums distincts : on peut avoir une maladie mentale et un bon niveau de santé mentale."},
{t:"vf",q:"D'après le schéma de Psycom, une personne qui souffre d'une maladie mentale peut jouir d'un niveau élevé de santé mentale.",a:true,e:"Et inversement, une personne sans maladie mentale peut avoir un faible niveau de santé mentale."},
{t:"trou",q:"La santé mentale est une composante de la santé de chaque individu : il faut prendre en compte les ressources et les ___ de chacun, internes et externes.",o:["obstacles","diagnostics","traitements","droits"],a:0,e:"Travailler sur les ressources et obstacles propres à chacun, et sur le contexte socio-politique."}]},
{id:"u4l2",title:"Trouble, maladie, handicap",q:[
{t:"qcm",q:"Pourquoi parle-t-on aujourd'hui de « troubles psychiques » plutôt que de « maladie mentale » ?",o:["Pour éviter la confusion entre handicap psychique et handicap mental, et dans une visée déstigmatisante","Parce que la loi interdit le mot maladie","Parce que les troubles sont toujours légers","Pour désigner uniquement la schizophrénie"],a:0,e:"Le handicap mental est associé à une déficience intellectuelle ; le handicap psychique aux troubles psychiques."},
{t:"vf",q:"Toutes les personnes ayant un trouble psychique ont un handicap psychique.",a:false,e:"Seulement celles pour qui le trouble est facteur d'un obstacle durable à la participation sociale dans un environnement donné."},
{t:"assoc",q:"Associe chaque handicap à son origine.",p:[["Handicap psychique","un trouble psychique (psychose, dépression, TOC, anxiété…)"],["Handicap mental","une déficience intellectuelle, souvent de naissance"],["Handicap cognitif","le fonctionnement des fonctions cognitives (attention, mémoire, langage…)"]],e:"Distinction clé du cours de Delphine Moreau."},
{t:"qcm",q:"Quelle loi définit le handicap comme « toute limitation d'activité ou restriction de participation à la vie en société subie dans un environnement… » ?",o:["La loi du 11 février 2005","La loi du 30 juillet 1838","La loi du 27 juin 1990","La loi du 26 janvier 2016"],a:0,e:"Loi pour l'égalité des droits et des chances, la participation et la citoyenneté des personnes handicapées. Elle cite les fonctions psychiques."},
{t:"vf",q:"Un handicap peut évoluer dans le temps, selon ce qui le cause, dont l'environnement de la personne.",a:true,e:"Le handicap se joue dans l'interaction avec l'environnement."},
{t:"qcm",q:"Par rapport aux « troubles », la notion de « maladie psychique » est associée à…",o:["une notion de sévérité et de troubles suffisamment caractérisés pour être diagnostiqués","des symptômes passagers sans gravité","l'absence de diagnostic","un handicap mental"],a:0,e:"Troubles = notion plus large."},
{t:"trou",q:"Folie > maladie mentale > psychique : chaque changement de mot vise à déstigmatiser, mais on observe un effet de ___ du stigmate.",o:["report","disparition","renforcement","partage"],a:0,e:"Le stigmate se reporte sur le nouveau mot : il persiste."}]},
{id:"u4l3",title:"Quelques chiffres",q:[
{t:"qcm",q:"Selon Wittchen et al. (2011), quelle part de la population européenne de 16 à 85 ans a eu un trouble psychique courant dans les 12 derniers mois ?",o:["27,1 %","7,8 %","50 %","1,2 %"],a:0,e:"Troubles anxieux 14 %, dépressifs et bipolaires 7,8 %, liés à une substance 4,6 %, psychotiques 1,2 %."},
{t:"assoc",q:"Associe chaque type de trouble à sa prévalence sur 12 mois (Wittchen et al., 2011).",p:[["Troubles anxieux","14 %"],["Troubles dépressifs et bipolaires","7,8 %"],["Troubles liés à une substance","4,6 %"],["Troubles psychotiques","1,2 %"]],e:"Dont 3,4 % de dépendance à l'alcool."},
{t:"qcm",q:"Quel est le trouble le plus fréquent dans l'étude de Wittchen ?",o:["Les troubles anxieux","Les troubles psychotiques","La dépendance à l'alcool","Les troubles bipolaires"],a:0,e:"14 % de la population de 16 à 85 ans sur 12 mois."},
{t:"qcm",q:"Prévalence citée dans le cours pour la schizophrénie ?",o:["1 %","10 %","25 %","0,01 %"],a:0,e:"Schizophrénie 1 %, troubles bipolaires 1 à 2 %, troubles anxio-dépressifs jusqu'à 25 %."},
{t:"vf",q:"La santé mentale est le premier poste de dépense de l'Assurance maladie.",a:true,e:"20 milliards d'euros pour le régime général, 23 milliards avec les autres régimes, 14 % des dépenses."},
{t:"qcm",q:"Combien de personnes l'Assurance maladie (CNAM, 2019) compte-t-elle dans le « poids » de la santé mentale ?",o:["Plus de sept millions","Environ 92 000","Environ 9 000","Deux cent mille"],a:0,e:"Plus de sept millions de personnes concernées par une consommation de soins."},
{t:"vf",q:"Diagnostic et mal-être, c'est la même chose dans les enquêtes épidémiologiques.",a:false,e:"Attention à la différence : auto-déclaration, tests ou diagnostic reçu, ce dernier dépendant de l'accès aux soins."},
{t:"qcm",q:"Laquelle de ces enquêtes est citée pour évaluer bien-être et mal-être en population ?",o:["Le Baromètre santé, EnCLASS, Enabee","Le recensement agricole","L'enquête emploi","Le PMSI"],a:0,e:"Enquêtes en population générale ou spécifique (détenus, sans domicile, jeunes…)."}]}
]},
{id:"u5",n:5,c:"--u5",title:"Promouvoir la santé mentale",who:"Delphine Moreau · leviers d'action",lessons:[
{id:"u5l1",title:"Une affaire collective",q:[
{t:"qcm",q:"Selon le cours, la promotion de la santé mentale inclut des programmes de prévention, mais aussi et d'abord…",o:["la promotion des droits, la lutte contre l'exclusion et la stigmatisation, l'accessibilité et la cohérence de la prévention et du soin","la construction d'hôpitaux psychiatriques","la prescription de médicaments","le dépistage génétique"],a:0,e:"La dimension collective et politique vient en premier."},
{t:"qcm",q:"Que critique la notion de « santémentalisation » des problèmes sociaux ?",o:["L'individualisation et la psychologisation, au lieu de prendre en compte les dimensions collectives, sociales et politiques","Le manque de psychiatres","La prise en compte des conditions de vie","Les campagnes nationales"],a:0,e:"Conclusion : la santé mentale n'est pas l'affaire que des « spécialistes de la santé mentale »."},
{t:"vf",q:"Selon l'OMS, les politiques nationales de santé mentale doivent se limiter aux troubles mentaux.",a:false,e:"Elles doivent aussi prendre en compte les facteurs plus généraux qui favorisent la santé mentale."},
{t:"qcm",q:"Selon l'OMS, la promotion de la santé mentale repose pour une large part sur des stratégies…",o:["intersectorielles","exclusivement médicales","hospitalières","individuelles"],a:0,e:"Éducation, emploi, justice, transports, environnement, logement, protection sociale."},
{t:"qcm",q:"Lequel de ces secteurs N'EST PAS cité par l'OMS parmi ceux à associer ?",o:["La défense nationale","L'éducation","Le logement","La justice"],a:0,e:"Secteurs cités : éducation, emploi, justice, transports, environnement, logement et protection sociale."},
{t:"vf",q:"Pour l'OMS, sans la sécurité et la liberté apportées par les droits fondamentaux, il est très difficile de conserver une bonne santé mentale.",a:true,e:"Droits civils, politiques, socioéconomiques et culturels."},
{t:"assoc",q:"Associe chaque exemple d'intervention de l'OMS à son domaine.",p:[["Visites à domicile pour les femmes enceintes","petite enfance"],["Microcrédit","autonomie socioéconomique des femmes"],["Programmes de prévention du stress","lieu de travail"],["Réduire l'accès à l'alcool et aux armes","prévention de la violence"]],e:"L'OMS donne une longue liste d'interventions, bien au-delà du soin."}]},
{id:"u5l2",title:"Stigmatisation et outils",q:[
{t:"qcm",q:"L'iceberg des discriminations de Psycom distingue trois niveaux. Lequel est le socle, souvent inconscient ?",o:["La culture","Les relations","Les institutions","Les médias"],a:0,e:"Relations (visible), institutions, culture (socle invisible, qui entraîne les deux autres)."},
{t:"assoc",q:"Associe chaque niveau de l'iceberg Psycom à son exemple.",p:[["Relations","des agressions racistes ou sexistes"],["Institutions","refuser un prêt bancaire à une personne diagnostiquée bipolaire"],["Culture","le préjugé « les personnes déprimées sont paresseuses »"]],e:"Il existe un cercle vicieux entre ces trois niveaux."},
{t:"qcm",q:"Quel auteur a écrit Stigmate. Les usages sociaux des handicaps ?",o:["Erving Goffman","Michel Foucault","Robert Castel","Albert Bandura"],a:0,e:"Goffman (1975 pour l'édition française). Il a aussi écrit Asiles."},
{t:"qcm",q:"Le « Cosmos mental » de Psycom est…",o:["un support d'échange pour mieux se connaître et identifier ses ressources (personnes, forces, dispositifs)","une échelle de diagnostic","un service d'urgence","une loi"],a:0,e:"Une modélisation de la santé mentale pour « parler santé mentale »."},
{t:"ordre",q:"Remets dans l'ordre le geste des Premiers secours en santé mentale (AERER).",items:["Approcher","Écouter","Réconforter","Encourager","Renseigner"],e:"A-E-R-E-R : on peut tous « parler santé mentale » et aller vers."},
{t:"vf",q:"Plan de rétablissement, plan de crise et directives anticipées sont des outils pour identifier et développer des ressources.",a:true,e:"Exemple : le kit « Mon GPS » de Psycom."},
{t:"qcm",q:"Quelles conditions sociales le cours demande-t-il de prendre en compte ?",o:["Accès aux droits, précarité sociale et juridique, violences, bouleversements du contexte de vie","Seulement les antécédents familiaux","Seulement l'âge","Le niveau de diplôme uniquement"],a:0,e:"Quatre conditions sociales listées par Delphine Moreau."}]},
{id:"u5l3",title:"Un contexte favorable",q:[
{t:"qcm",q:"Selon l'article L. 3221-1 issu de la loi de 2016, la politique de santé mentale comprend…",o:["des actions de prévention, de diagnostic, de soins, de réadaptation et de réinsertion sociale","seulement des soins hospitaliers","seulement la prévention du suicide","les soins sans consentement uniquement"],a:0,e:"Mise en œuvre par des acteurs diversifiés : psychiatrie, libéraux, psychologues, prévention, logement, hébergement, insertion."},
{t:"vf",q:"Avec la loi de 2016, la santé mentale n'est plus du seul ressort de la psychiatrie et des professionnels « psy ».",a:true,e:"Les acteurs du logement, de l'hébergement et de l'insertion sont cités."},
{t:"qcm",q:"La feuille de route « Psychiatrie et santé mentale » date de…",o:["juin 2018","juillet 1838","mars 1960","septembre 2021"],a:0,e:"28 juin 2018 ; bilans en mars 2023 et mai 2025."},
{t:"assoc",q:"Associe chaque axe de la feuille de route 2018 à un exemple.",p:[["Promouvoir le bien-être mental et prévenir","Premiers secours en santé mentale, 3114"],["Parcours de soins coordonnés","offre en psychiatrie accessible, diversifiée, de qualité"],["Inclusion","conditions de vie et citoyenneté des personnes en situation de handicap psychique"]],e:"Trois axes : promotion et prévention, parcours, inclusion."},
{t:"qcm",q:"Combien de mesures ont été annoncées aux Assises de la santé mentale de septembre 2021 ?",o:["30","3","114","12"],a:0,e:"Assises des 27 et 28 septembre 2021 : 30 mesures."},
{t:"vf",q:"La santé mentale a été déclarée grande cause nationale en 2025.",a:true,e:"« Parlons santé mentale »."},
{t:"qcm",q:"Le plan « Santé mentale et psychiatrie : repérer, soigner, reconstruire » date de…",o:["juin 2025","juin 2018","janvier 2016","mars 2023"],a:0,e:"Cité dans les lois et plans du document ressources."}]}
]},
{id:"u6",n:6,c:"--u6",title:"Prévenir le suicide",who:"Delphine Moreau · prévention du suicide",lessons:[
{id:"u6l1",title:"Chiffres et facteurs",q:[
{t:"qcm",q:"Combien de personnes se suicident chaque année en France environ ?",o:["9 000","900","90 000","3 114"],a:0,e:"Taux de 13,3 pour 100 000, l'un des plus élevés d'Europe (moyenne 10,6)."},
{t:"qcm",q:"Taux de suicide en France comparé à la moyenne européenne ?",o:["13,3 contre 10,6 pour 100 000","10,6 contre 13,3 pour 100 000","5 contre 20 pour 100 000","Identique"],a:0,e:"La France reste l'un des pays les plus touchés d'Europe."},
{t:"vf",q:"Les hommes se suicident environ 3,7 fois plus que les femmes.",a:true,e:"Le plus grand nombre de suicides chez les 45-54 ans ; taux doublé après 75 ans."},
{t:"qcm",q:"Chez les 15-25 ans, le suicide est…",o:["la 2e cause de mortalité, après les blessures involontaires","la 1re cause de mortalité","la 5e cause","une cause rare"],a:0,e:"1re cause : blessures involontaires."},
{t:"qcm",q:"Quelles régions sont les plus touchées par le suicide (2014-2016) ?",o:["Bretagne, Pays de la Loire, Normandie et Hauts-de-France","Île-de-France, Corse, Auvergne-Rhône-Alpes","Occitanie et PACA","Grand Est et Bourgogne"],a:0,e:"Plus de 30 % au-dessus du taux national. Les moins touchées : Auvergne-Rhône-Alpes, Corse, Île-de-France."},
{t:"vf",q:"Les écarts régionaux de suicide reflètent toujours fidèlement la situation épidémiologique réelle.",a:false,e:"À comparer avec prudence : défaut d'exhaustivité et qualité inégale de la remontée d'information."},
{t:"qcm",q:"Quelle part des personnes décédées par suicide présentaient une pathologie psychiatrique ?",o:["90 %, dont 60 % de troubles dépressifs","50 %","10 %","100 %"],a:0,e:"Sur-suicidalité avec la schizophrénie, les troubles bipolaires et la dépendance à l'alcool."},
{t:"assoc",q:"Range ces facteurs de risque suicidaire dans leur catégorie.",p:[["Troubles dépressifs","troubles psychiatriques"],["Isolement","vulnérabilité sociale"],["Antécédents familiaux","vulnérabilité sociale"],["Geste suicidaire passé","tentative antérieure"]],e:"Trois familles : troubles psychiatriques, vulnérabilité sociale, tentative antérieure."}]},
{id:"u6l2",title:"Niveaux et politiques",q:[
{t:"assoc",q:"Associe chaque niveau de prévention à son public.",p:[["Universelle","l'ensemble de la population"],["Sélective","une population vulnérable"],["Indiquée","les suicidant·es"]],e:"Trois niveaux de prévention du cours."},
{t:"qcm",q:"La prévention « indiquée » du suicide s'adresse à…",o:["les suicidant·es","l'ensemble de la population","une population vulnérable","les professionnels de santé"],a:0,e:"Universelle : toute la population. Sélective : une population vulnérable. Indiquée : les suicidant·es."},
{t:"vf",q:"Le suicide est reconnu comme un enjeu de santé publique en France dès les années 1990.",a:true,e:"Puis la Stratégie nationale d'action face au suicide 2000-2005."},
{t:"qcm",q:"Lequel N'EST PAS un objectif de la Stratégie nationale d'action face au suicide 2000-2005 ?",o:["Créer le numéro 3114","Diminuer l'accès aux moyens létaux","Améliorer la prise en charge","Approfondir la connaissance épidémiologique"],a:0,e:"Le 3114 date de septembre 2021. Le 4e objectif : favoriser la prévention par un dépistage accru des risques."},
{t:"ordre",q:"Remets dans l'ordre les étapes de la politique de prévention du suicide.",items:["Stratégie nationale d'action face au suicide (2000-2005)","Loi HPST : compétence régionale (2009)","Programme national d'actions contre le suicide (2011-2014)","Stratégie multimodale (2019)"],e:"La stratégie multimodale est intégrée à la feuille de route 2018 (axe 1, action 6)."},
{t:"vf",q:"En 2011-2014, le programme contre le suicide était distinct du Plan psychiatrie et santé mentale.",a:true,e:"Depuis la feuille de route 2018, la prévention du suicide y est intégrée."},
{t:"trou",q:"La loi ___ de 2009 fait entrer la prévention du suicide dans le champ de compétence régional (PRS).",o:["HPST","Evin","Kouchner","Veil"],a:0,e:"Hôpital, patients, santé et territoires."}]},
{id:"u6l3",title:"La stratégie multimodale",q:[
{t:"qcm",q:"Lequel de ces éléments fait partie des 5 actions de la stratégie multimodale de 2019 ?",o:["Le maintien du contact avec la personne qui a fait une tentative de suicide","La fermeture des lignes d'écoute","Le dépistage génétique","La suppression des urgences psychiatriques"],a:0,e:"Maintien du contact, formation, prévention de la contagion, 3114, information du public."},
{t:"qcm",q:"Le numéro national de prévention du suicide 3114 a été mis en place en…",o:["septembre 2021, coordonné par le CHU de Lille","2000","2009","2016"],a:0,e:"Pour les personnes avec idées suicidaires, leurs proches, les endeuillés et les professionnels."},
{t:"qcm",q:"Le programme Papageno vise à…",o:["prévenir la contagion suicidaire, éviter l'« effet Werther »","recontacter les suicidants","former les sentinelles","financer les lignes d'écoute"],a:0,e:"Il agit notamment sur la manière de parler du suicide dans les médias."},
{t:"qcm",q:"Le programme VigilanS consiste à…",o:["recontacter les personnes suicidaires (post-vention)","former les étudiants aux premiers secours","coordonner le 3114","éviter l'effet Werther"],a:0,e:"Il correspond au maintien du contact après une tentative."},
{t:"assoc",q:"Associe chaque rôle de la formation au repérage à sa fonction.",p:[["Sentinelle","repérer et orienter"],["Évaluateur","évaluer cliniquement le potentiel suicidaire et orienter"],["Intervenant de crise","évaluer cliniquement et intervenir"]],e:"Trois niveaux de formation au repérage et à l'orientation."},
{t:"qcm",q:"Laquelle de ces lignes d'écoute est destinée aux étudiants ?",o:["Nightline","SOS Amitié","SOS Suicide","Le 15"],a:0,e:"Lignes locales ou nationales, privées ou publiques, générales ou ciblées."},
{t:"vf",q:"Selon le cours, la prévention du suicide passe aussi par la promotion de la santé mentale en général.",a:true,e:"Promotion générale + dispositifs spécifiques de prévention du suicide."},
{t:"qcm",q:"Sur quels dispositifs locaux s'appuie la coordination des acteurs de prévention du suicide ?",o:["Les CLSM, les CLS et les PTSM","Les tribunaux","Les CHU uniquement","Les mairies d'arrondissement seulement"],a:0,e:"Conseils locaux de santé mentale, contrats locaux de santé, projets territoriaux de santé mentale."},
{t:"qcm",q:"Lequel N'EST PAS un objectif des programmes de prévention du suicide (UNPS) ?",o:["Augmenter le nombre de lits fermés","Promouvoir des milieux de vie favorables","Sécuriser les environnements à risque","Soutenir les approches citoyennes et associatives"],a:0,e:"Aussi : renforcer les facteurs de protection, maintenir le contact, former au repérage."}]}
]},
/* ================= MOREAU : POLITIQUES ================= */
{id:"u7",n:7,c:"--u7",title:"De l'asile au secteur",who:"Delphine Moreau · politiques de santé mentale",lessons:[
{id:"u7l1",title:"La loi de 1838",q:[
{t:"qcm",q:"Que crée la loi du 30 juillet 1838, dite « sur les aliénés » ?",o:["Un cadre légal des placements d'office et volontaires, un asile par département, la prise en charge des aliénés indigents","Le secteur psychiatrique","Les soins sans consentement en ambulatoire","Le contrôle du juge des libertés"],a:0,e:"Médicalisation des internements contre l'arbitraire des lettres de cachet."},
{t:"vf",q:"La loi de 1838 prévoit un asile par département.",a:true,e:"C'est la première loi d'organisation territoriale des soins."},
{t:"qcm",q:"Contre quoi la loi de 1838 médicalise-t-elle les internements ?",o:["L'arbitraire des lettres de cachet","Les dépenses des départements","La surpopulation des prisons","Les épidémies"],a:0,e:"Elle définit conditions, certificat, recours et contrôle."},
{t:"qcm",q:"Quel problème apparaît dès la fin du XIXe siècle ?",o:["Le surencombrement des asiles, une charge financière pour les départements","La fermeture des asiles","Le manque de patients","L'arrivée des neuroleptiques"],a:0,e:"Surencombrement des asiles."},
{t:"trou",q:"Le dispositif de 1838 est « ___ » : soin, enfermement et statut civil y sont liés (Eyraud, Moreau, 2013).",o:["encastré","sectorisé","ambulatoire","inclusif"],a:0,e:"L'histoire du XXe siècle est celle du « désencastrement »."},
{t:"qcm",q:"Le « désencastrement » du XXe siècle, c'est…",o:["la distinction progressive entre soin, enfermement, hospitalisation et statut : services libres, consultations extrahospitalières","le retour aux lettres de cachet","la fermeture de tous les hôpitaux","la création des prisons"],a:0,e:"Dispensaires d'hygiène mentale, services libres, ouverture de pavillons, sorties."}]},
{id:"u7l2",title:"Après-guerre et secteur",q:[
{t:"qcm",q:"Combien de malades mentaux sont morts de faim dans les hôpitaux psychiatriques sous l'Occupation selon I. von Bueltzingsloewen ?",o:["40 000","4 000","400 000","92 000"],a:0,e:"L'« hécatombe des fous », qui relance la critique asilaire."},
{t:"qcm",q:"Quelle expérience fondatrice est citée pour l'après-guerre ?",o:["Saint-Alban et la psychothérapie institutionnelle","Le Vinatier sécurisé","Un chez-soi d'abord","Le programme Papageno"],a:0,e:"Elle montre les capacités de ceux qui étaient perçus comme incapables."},
{t:"vf",q:"Le renouveau de la critique asilaire après 1945 dénonce la chronicisation due à l'institutionnalisation.",a:true,e:"Avec l'hécatombe des fous et l'expérience de Saint-Alban."},
{t:"qcm",q:"Quels textes créent le secteur psychiatrique ?",o:["La circulaire du 15 mars 1960 et la loi de 1985","La loi de 1838","La loi de 2005","La loi HPST de 2009"],a:0,e:"Promotion du soin « dans la cité »."},
{t:"qcm",q:"Quelle population couvre une équipe de secteur ?",o:["Entre 70 000 et plus de 200 000 habitants","1 000 habitants","Un département entier","Un pays"],a:0,e:"Un territoire « géo-populationnel », au lieu d'une organisation par pathologie, agitation ou curabilité."},
{t:"vf",q:"Le secteur organise les soins par pathologie.",a:false,e:"Il s'organise par territoire géo-populationnel, pas par pathologie."},
{t:"qcm",q:"Que doit organiser une équipe de secteur ?",o:["La prévention, le dépistage, la prise en charge hospitalière et ambulatoire, la réadaptation et la réinsertion","Seulement l'hospitalisation","Seulement les urgences","Seulement les soins sans consentement"],a:0,e:"Une continuité du dépistage à la réinsertion."},
{t:"qcm",q:"En 1968, qu'est-ce qui est distingué ?",o:["La mesure de protection des majeurs et le placement contraint","Le soin libre et le soin contraint","Le handicap mental et psychique","Le secteur et le pôle"],a:0,e:"Une étape du désencastrement entre statut civil et enfermement."}]},
{id:"u7l3",title:"Les structures du secteur",q:[
{t:"assoc",q:"Associe chaque sigle à sa signification.",p:[["CMP","centre médico-psychologique"],["CATTP","centre d'activité thérapeutique à temps partiel"],["HDJ","hôpital de jour"],["CAC","centre d'accueil et de crise"]],e:"Les structures du secteur autour du service d'hospitalisation."},
{t:"qcm",q:"Quelle structure est présentée comme le « pivot du secteur » ?",o:["Le CMP","Le CATTP","L'hôpital de jour","Le service d'hospitalisation"],a:0,e:"Le cours pose la question : le CMP, « pivot du secteur » ?"},
{t:"qcm",q:"D'après l'article L. 3211-1 du CSP, une personne en soins psychiatriques…",o:["peut s'adresser au praticien ou à l'équipe de son choix, dans ou hors de son secteur","doit être suivie par son secteur de résidence","ne peut pas choisir son psychiatre","ne peut consulter qu'en libéral"],a:0,e:"Libre choix, publique ou privée, à l'intérieur ou à l'extérieur du secteur."},
{t:"qcm",q:"Laquelle N'EST PAS une limite du secteur citée en cours ?",o:["Un excès de moyens donnés à l'extra-hospitalier","Le rôle « dans la cité » pas toujours investi","La persistance de la psychiatrie comme spécialiste quasi exclusive","Un hospitalocentrisme critiqué"],a:0,e:"C'est l'inverse : les moyens donnés à l'accompagnement extra-hospitalier sont insuffisants."},
{t:"assoc",q:"Associe chaque composante des soins psychiatriques à un exemple.",p:[["Sectorisée","services de psychiatrie d'hôpitaux publics et ESPIC"],["Non sectorisée","cliniques privées à but lucratif"],["Exclusivement ambulatoire","cabinets de psychiatres libéraux"]],e:"La composante sectorisée est la plus importante."},
{t:"vf",q:"La composante sectorisée est la plus importante des trois composantes des soins psychiatriques.",a:true,e:"Établissements publics et ESPIC (ex. Sainte-Marie à Nice, La Verrière)."},
{t:"qcm",q:"Quels dispositifs remboursent des consultations de psychologue ?",o:["« Mon soutien psy » et « Santé psy étudiant »","Le 3114","VigilanS","Les GEM"],a:0,e:"L'enjeu du remboursement des psychologues."},
{t:"qcm",q:"En Seine-Saint-Denis, quel hôpital gère la majorité des secteurs adultes ?",o:["Le CHS de Ville-Évrard","L'hôpital Ballanger","Le Vinatier","Sainte-Marie"],a:0,e:"Ville-Évrard gère les secteurs 1 à 18 sauf 7, 8 et 17, confiés à l'hôpital Ballanger. Configurations variées : une ville pour un secteur, plusieurs villes pour un secteur, une ville pour plusieurs secteurs."}]}
]},
{id:"u8",n:8,c:"--u8",title:"Contrainte et droits",who:"Delphine Moreau · soins sans consentement",lessons:[
{id:"u8l1",title:"Trois lois, trois vocabulaires",q:[
{t:"assoc",q:"Associe chaque loi au vocabulaire de la contrainte qu'elle introduit.",p:[["Loi de 1838","placement d'office, placement volontaire"],["Loi de 1990","hospitalisation d'office, à la demande d'un tiers, libre"],["Loi de 2011","SDRE, SDT, péril imminent, soins libres"]],e:"PO/PV → HO/HDT/HL → SDRE/SDT/SPI/SL."},
{t:"qcm",q:"Que signifie SDRE ?",o:["Soins sur décision du représentant de l'État","Soins dans un établissement","Service de réhabilitation","Soins de durée réduite"],a:0,e:"Successeur de l'hospitalisation d'office et du placement d'office."},
{t:"qcm",q:"Sous la loi de 1990, combien de certificats médicaux faut-il pour une hospitalisation à la demande d'un tiers ?",o:["Deux, plus la demande d'un tiers","Un seul","Aucun","Trois"],a:0,e:"L'hospitalisation d'office demande un certificat médical."},
{t:"qcm",q:"La procédure de « péril imminent » de la loi de 2011 permet…",o:["des soins sur demande d'un tiers sans tiers","des soins libres","une hospitalisation de 12 jours sans contrôle","une admission par le préfet seul"],a:0,e:"SDT – péril imminent : sans tiers."},
{t:"vf",q:"La loi du 27 juin 1990 introduit le soin libre dans la loi : la contrainte doit être l'exception.",a:true,e:"Elle rappelle aussi les droits des personnes hospitalisées."},
{t:"qcm",q:"Dans le tableau du cours, quelle autorité décide d'un placement d'office (1838) ou de soins SDRE (2011) ?",o:["Le représentant de l'État","Le directeur d'établissement","Le juge des enfants","La famille"],a:0,e:"Le directeur d'établissement admet en placement volontaire / HDT / SDT."},
{t:"ordre",q:"Remets dans l'ordre chronologique ces lois sur la contrainte.",items:["Loi sur les aliénés (1838)","Loi sur les droits des personnes hospitalisées (1990)","Loi sur les soins psychiatriques (2011)","Modification de la loi de 2011 (2013)"],e:"30 juillet 1838 → 27 juin 1990 → 5 juillet 2011 → 27 septembre 2013."}]},
{id:"u8l2",title:"La loi de 2011",q:[
{t:"qcm",q:"Quelle nouveauté majeure la loi du 5 juillet 2011 introduit-elle ?",o:["Les soins ambulatoires sans consentement (programmes de soins) et le contrôle systématique du juge des libertés","Le soin libre","Un asile par département","Le secteur"],a:0,e:"Contrôle des hospitalisations à temps complet de plus de 12 jours."},
{t:"qcm",q:"Le juge des libertés contrôle systématiquement les hospitalisations sans consentement au-delà de…",o:["12 jours","72 heures","1 mois","6 mois"],a:0,e:"Hospitalisation d'au moins 72 h si confirmée, contrôle du JLD au-delà de 12 jours."},
{t:"trou",q:"Loi 2011 : hospitalisation d'au minimum ___ si elle est confirmée, puis éventuel programme de soins.",o:["72 heures","12 jours","24 heures","1 semaine"],a:0,e:"72 h minimum, contrôle du juge au-delà de 12 jours."},
{t:"qcm",q:"Combien de personnes ont été prises en charge en soins sans consentement en 2015 ?",o:["92 000, soit 12 000 de plus qu'en 2012","9 000","424 000","40 000"],a:0,e:"Coldefy et al., 2017."},
{t:"qcm",q:"Comment Coldefy et al. (2017) expliquent-ils la hausse des soins sans consentement ?",o:["Par l'extension de leur durée hors de l'hôpital (programmes de soins) et la montée des soins pour péril imminent","Par la hausse de la population","Par la fermeture des CMP","Par la loi de 1838"],a:0,e:"Deux facteurs explicatifs à retenir."},
{t:"vf",q:"Un programme de soins est un soin sans consentement en ambulatoire.",a:true,e:"La contrainte se déploie hors des murs de l'hôpital (Moreau, Marques, 2020)."},
{t:"qcm",q:"Par quelle loi la loi de 2011 a-t-elle été modifiée ?",o:["La loi du 27 septembre 2013","La loi du 26 janvier 2016","La loi du 11 février 2005","La loi du 24 juillet 2019"],a:0,e:"Loi n° 2013-869."}]},
{id:"u8l3",title:"Encadrer, réduire, respecter",q:[
{t:"qcm",q:"Quel organisme de contrôle est créé en 2008 ?",o:["Le CGLPL, Contrôleur général des lieux de privation de liberté","Le CCNE","La HAS","Santé publique France"],a:0,e:"Il renforce l'encadrement des contraintes."},
{t:"qcm",q:"Quelle loi est la première régulation légale du recours à l'isolement et à la contention ?",o:["La loi du 26 janvier 2016","La loi de 1990","La loi de 2005","La loi de 1838"],a:0,e:"Loi de modernisation de notre système de santé."},
{t:"vf",q:"L'encadrement de la contrainte à la fois traduit une vigilance et légitime les pratiques.",a:true,e:"Le cours pointe cette ambivalence."},
{t:"qcm",q:"Selon le cours, le focus porte souvent sur le contrôle de la contrainte plutôt que sur…",o:["la recherche d'alternatives ou d'un moindre recours","le nombre de psychiatres","les budgets hospitaliers","les médicaments"],a:0,e:"Alternatives : plan de crise conjoint, directives anticipées, Open dialogue, rétablissement, aller-vers."},
{t:"qcm",q:"Laquelle de ces pratiques est citée comme alternative à la contrainte ?",o:["Le plan de crise conjoint","La contention","L'isolement","Le placement d'office"],a:0,e:"Aussi : directives anticipées, Open dialogue."},
{t:"qcm",q:"La Convention relative aux droits des personnes handicapées (ONU) a été…",o:["adoptée en 2006 et ratifiée par la France en 2010","adoptée en 1975","ratifiée par la France en 2005","adoptée en 2016"],a:0,e:"La rapporteuse spéciale Catalina Devandas-Aguilar a visité la France en 2017."},
{t:"vf",q:"La CRDPH se limite aux personnes reconnues handicapées par l'administration.",a:false,e:"Pas de définition restrictive : elle porte sur toute restriction de liberté et de reconnaissance de l'égale personnalité juridique."},
{t:"qcm",q:"Que recommande l'ONU à la France dans ses conclusions de 2021 ?",o:["Une société réellement inclusive, contre l'institutionnalisation et les formes de contrainte","Plus de lits fermés","Plus de foyers spécialisés","Un retour à la loi de 1838"],a:0,e:"Contre les foyers, l'éducation et le travail protégés, les soins sans consentement, la protection des majeurs."},
{t:"ordre",q:"Remets dans l'ordre ces étapes vers un meilleur respect des droits.",items:["Lois sur les droits des usagers (2002)","Création du CGLPL (2008)","Visite du CPT du Conseil de l'Europe (2010)","Loi de 2011 : contrôle du juge"],e:"Puis 2016 : régulation de l'isolement et de la contention."}]}
]},
{id:"u9",n:9,c:"--u9",title:"Territoires, handicap, usagers",who:"Delphine Moreau · nouveaux axes et repères",lessons:[
{id:"u9l1",title:"Moins de lits, nouvelles demandes",q:[
{t:"qcm",q:"De combien a baissé le nombre de lits en psychiatrie entre 1976 et 2016 ?",o:["-60 %","-10 %","-90 %","-25 %"],a:0,e:"Avec des transferts de fait vers le social, le médico-social, les familles, la rue et la prison."},
{t:"vf",q:"La diminution des lits s'est accompagnée de transferts de fait vers la rue et la prison.",a:true,e:"Et vers le social, le médico-social et les solidarités privées (familles)."},
{t:"qcm",q:"Quelle part des patients est prise en charge exclusivement en ambulatoire ?",o:["87 %","13 %","50 %","23 %"],a:0,e:"2,1 millions de patients en ambulatoire, 21,3 millions d'actes (ATIH)."},
{t:"qcm",q:"Où se réalisent la majorité des actes ambulatoires en psychiatrie publique ?",o:["En CMP (59 %)","À domicile (6 %)","En CATTP (13 %)","En liaison médico-sociale (1 %)"],a:0,e:"59 % en CMP, 13 % en CATTP, 6 % à domicile."},
{t:"qcm",q:"Combien de patients ont été hospitalisés en psychiatrie en 2018 (ATIH) ?",o:["424 000, soit 6 pour 1 000 habitants","92 000","2,1 millions","40 000"],a:0,e:"Dont 49 000 enfants, 360 000 adultes de 18 à 79 ans, 15 000 personnes de 80 ans ou plus."},
{t:"qcm",q:"Que désigne l'interrogation sur une « médicalisation du social » ?",o:["L'augmentation des demandes sociales adressées à la psychiatrie (souffrance sociale, travail, trauma)","La baisse des dépenses de santé","La fermeture des CMP","Le remboursement des psychologues"],a:0,e:"L'expression de la souffrance comme une manière de mettre en mots des rapports sociaux ?"},
{t:"qcm",q:"La réforme des autorisations en psychiatrie (décrets 2022, mise en œuvre 2023) fixe le seuil entre psychiatrie de l'enfant et de l'adulte à…",o:["18 ans","16 ans","15 ans","21 ans"],a:0,e:"Deux autres mentions : psychiatrie périnatale, soins sans consentement."},
{t:"qcm",q:"Quel est l'objectif de la réforme du financement de la psychiatrie (1er janvier 2022) ?",o:["Inciter à diminuer l'hospitalisation et valoriser les interventions intensives hors de l'établissement (équipes mobiles)","Augmenter le nombre de lits","Supprimer les CMP","Financer les cliniques privées uniquement"],a:0,e:"Accompagner les transformations."},
{t:"qcm",q:"Selon l'enquête FHF 2023, quelle part des établissements a dû fermer de 10 à 30 % de lits fin 2022 ?",o:["Près d'un quart (24 %)","8 %","La moitié","Aucun"],a:0,e:"Crise RH : 1/3 des établissements ont 25 à 49 % de postes de psychiatres vacants."}]},
{id:"u9l2",title:"Nouveaux territoires",q:[
{t:"assoc",q:"Associe chaque dispositif territorial à son échelle.",p:[["CLSM","~ la ville"],["PTSM","~ le département"],["GHT","le groupement hospitalier de territoire"]],e:"Loi de 2016 : juxtaposition et recouvrement de différents territoires."},
{t:"qcm",q:"Que produit le projet territorial de santé mentale (PTSM) ?",o:["Un diagnostic territorial","Un certificat médical","Une hospitalisation sous contrainte","Un remboursement de psychologue"],a:0,e:"Créé par la loi de 2016, précisé par la loi du 24 juillet 2019."},
{t:"vf",q:"Les conseils locaux de santé mentale (CLSM) ont été créés par la loi de 2016.",a:false,e:"Ils existaient déjà ; la loi encourage leur développement."},
{t:"qcm",q:"Qu'avait effacé une ordonnance de 2003 et que réintroduit la loi de 2016 ?",o:["La référence au secteur","Le soin libre","Le juge des libertés","Le CMP"],a:0,e:"Au profit des pôles, depuis la loi HPST de 2009 ; le secteur reste structurant sur certains territoires."},
{t:"qcm",q:"Le programme « Un chez-soi d'abord » repose sur l'idée que…",o:["le logement est un droit et une condition d'accès aux droits, non conditionné à l'acceptation des soins ou au sevrage","le logement est l'aboutissement d'un parcours réussi","il faut d'abord être soigné pour être logé","le logement relève de la psychiatrie"],a:0,e:"Approche « par les droits » contre approche « par les besoins »."},
{t:"vf",q:"Dans l'approche « par les besoins », le logement est l'aboutissement d'un parcours d'aide réussi.",a:true,e:"« Un chez-soi d'abord » l'inverse : le logement d'abord."},
{t:"trou",q:"La loi du 27 janvier 2016 introduit les territoires de santé mentale et le « logement ___ ».",o:["d'abord","social","adapté","protégé"],a:0,e:"Repère chronologique du document ressources."}]},
{id:"u9l3",title:"Handicap psychique et usagers",q:[
{t:"qcm",q:"La loi d'orientation de 1975 en faveur des personnes handicapées…",o:["ne définit pas le handicap","définit le handicap psychique","crée les GEM","crée le secteur"],a:0,e:"Son article 47 vise les « malades mentaux » qui ne nécessitent plus le maintien en hôpital."},
{t:"qcm",q:"Lequel N'EST PAS un frein cité à la reconnaissance d'un handicap lié aux troubles psychiques ?",o:["L'opposition des associations d'usagers","La crainte des psychiatres d'enfermer dans la catégorie de handicap","La réticence des conseils généraux face à un transfert de charge","La difficulté à faire reconnaître un « handicap invisible »"],a:0,e:"Les associations ont au contraire annoncé la « reconnaissance du handicap psychique » en 2005."},
{t:"qcm",q:"En 1998, quelle part des demandeurs d'allocation adulte handicapé le faisaient au motif d'une déficience psychique ?",o:["24,2 %, dont 78 % obtiennent un accord","78 %","5 %","50 %"],a:0,e:"Recours progressif aux dispositifs du handicap (Piel et Roelandt, 2001)."},
{t:"qcm",q:"Quels dispositifs la loi de 2005 crée-t-elle pour le handicap psychique ?",o:["Les GEM, SAVS et SAMSAH","Les CMP et CATTP","Le 3114 et VigilanS","Les CLSM et PTSM"],a:0,e:"Groupes d'entraide mutuelle, services d'accompagnement à la vie sociale, services médico-sociaux pour adultes handicapés."},
{t:"vf",q:"La démocratie sanitaire renforce des droits des usagers comme l'accès au dossier et le droit de refuser des soins.",a:true,e:"Lois de 2002 ; représentation des usagers (CDU, CLIN, CPP…)."},
{t:"qcm",q:"Que signifie MSP dans le champ de la santé mentale ?",o:["Médiateur de santé pair","Maison de santé pluriprofessionnelle","Mission de santé publique","Médecin spécialiste en psychiatrie"],a:0,e:"De l'expérience à l'expertise : MSP, pairs-aidants, patients-formateurs (Demailly, 2014)."},
{t:"qcm",q:"Laquelle de ces associations est citée parmi les associations d'usagers ou de proches ?",o:["L'UNAFAM","L'UNPS","La FHF","La HAS"],a:0,e:"UNAFAM, FNAPSY, Advocacy, REV…"},
{t:"qcm",q:"Quelle conclusion le cours tire-t-il ?",o:["Une intégration progressive de la psychiatrie dans le système commun, non sans écueils, avec persistance de la stigmatisation","La psychiatrie n'a pas changé depuis 1838","La contrainte a disparu","Le secteur est supprimé"],a:0,e:"Restent : tensions soins-sécurité-liberté, accès au soin somatique, inclusion et accès aux droits."}]},
{id:"u9l4",title:"Repères chronologiques",q:[
{t:"ordre",q:"Remets dans l'ordre ces repères de la psychiatrie à la santé mentale.",items:["Loi sur les aliénés (1838)","Circulaire du secteur (1960)","Loi d'orientation handicap (1975)","Loi sur les hospitalisations (1990)"],e:"Repères du document « Ressources santé mentale »."},
{t:"ordre",q:"Remets dans l'ordre ces repères récents.",items:["Loi du 11 février 2005 (handicap)","Loi HPST (2009)","Loi du 5 juillet 2011","Loi de modernisation (2016)","Feuille de route (2018)"],e:"Puis Assises 2021, réformes 2022, grande cause 2025."},
{t:"qcm",q:"Qu'est-ce qui est supprimé en 1992 ?",o:["Le diplôme d'infirmier de secteur psychiatrique, au profit du diplôme d'État","Le secteur","Les asiles","Le CMP"],a:0,e:"Repère chronologique du document ressources."},
{t:"qcm",q:"Le Plan d'action global pour la santé mentale de l'OMS couvre la période…",o:["2013-2030","2000-2005","2011-2015","2018-2025"],a:0,e:"Niveau international."},
{t:"qcm",q:"L'avis 147 du CCNE (9 janvier 2025) porte sur…",o:["les enjeux éthiques de la crise de la psychiatrie","la vaccination","le suicide des jeunes","le logement d'abord"],a:0,e:"« Une alerte du CCNE »."},
{t:"vf",q:"La loi du 4 mars 2002 est relative aux droits des malades et à la qualité du système de santé.",a:true,e:"Loi n° 2002-303 du 4 mars 2002."},
{t:"qcm",q:"Quelle revue de l'ORSPERE-SAMDARRA, en libre accès, traite de santé mentale et précarité ?",o:["Rhizome","La Santé en action","Esprit","Sociologos"],a:0,e:"Clinique psychosociale, précarité, migration, logement."},
{t:"qcm",q:"Quel site est présenté comme ressource sur les droits, la déstigmatisation et les soins ?",o:["Psycom","Doctolib","Ameli Pro","Légifrance"],a:0,e:"Brochures, outils pour parler santé mentale, cartographie des acteurs."}]}
]},
/* ================= RAUDE : QUESTIONNAIRE ================= */
{id:"u10",n:10,c:"--u10",title:"Construire un questionnaire",who:"Jocelyn Raude · méthodes quantitatives",lessons:[
{id:"u10l1",title:"Concevoir l'enquête",q:[
{t:"qcm",q:"Quelle conviction Rosenstock (1960) place-t-il au cœur de l'étude de la motivation ?",o:["Tout comportement est motivé","Le comportement est aléatoire","Seuls les experts sont motivés","La motivation ne se mesure pas"],a:0,e:"Si l'on identifie les motivations, on peut comprendre, prédire et contrôler le comportement."},
{t:"assoc",q:"Associe chaque approche à la question qu'elle pose.",p:[["Épidémiologie sociale","qui sont les personnes qui ont un comportement inapproprié ?"],["Psychologie","pourquoi certaines personnes se comportent-elles plus mal que d'autres ?"]],e:"Études sociodémographiques d'un côté, études motivationnelles (croyances, attitudes, normes) de l'autre."},
{t:"vf",q:"Les enquêtes collectent des informations de façon systématique pour produire des statistiques sur des groupes d'individus.",a:true,e:"Quartier, communauté, population."},
{t:"ordre",q:"Remets dans l'ordre les étapes de conception d'une enquête.",items:["Réfléchir à la question de santé publique","Définir les objectifs","Préciser les variables","Réfléchir aux relations entre variables","Choisir l'échantillonnage et la collecte","Formuler les items","Mettre en page puis administrer"],e:"Les huit étapes du cours, résumées en sept."},
{t:"assoc",q:"Range chaque élément : type d'enquête ou mode de collecte ?",p:[["Enquête longitudinale","type d'enquête"],["Enquête expérimentale","type d'enquête"],["Entretien téléphonique","mode de collecte"],["Enquête par courrier","mode de collecte"]],e:"Types : transversale, comparative, longitudinale, expérimentale. Modes : face à face, téléphone, en ligne, courrier."},
{t:"qcm",q:"Laquelle N'EST PAS une des questions de recherche fondamentales du cours ?",o:["Combien coûte l'enquête ?","Que souhaitez-vous découvrir ?","Qui souhaitez-vous étudier ?","Quand mener l'enquête ?"],a:0,e:"Aussi : où se trouvent les personnes, que comptez-vous apprendre et pourquoi."},
{t:"trou",q:"Des concepts comme le « capital social » doivent être traduits en définitions ___ : cadre conceptuel → variables → questions.",o:["opérationnelles","juridiques","narratives","statistiques"],a:0,e:"Passer du concept à la mesure."}]},
{id:"u10l2",title:"Variables et questions",q:[
{t:"assoc",q:"Associe chaque variable à son type.",p:[["Situation matrimoniale","nominale"],["Degré d'accord","ordinale"],["Cigarettes fumées par jour","d'intervalle ou de rapport"],["Niveau d'éducation formelle","ordinale"]],e:"Trois grands types de variables mesurables par questionnaire."},
{t:"qcm",q:"La religion ou la profession sont des variables…",o:["nominales","ordinales","d'intervalle","de rapport"],a:0,e:"Catégories sans ordre."},
{t:"qcm",q:"Une probabilité de 0 à 100 % est une variable…",o:["d'intervalle ou de rapport","nominale","ordinale","dichotomique"],a:0,e:"Comme l'âge, la taille, le revenu du foyer."},
{t:"assoc",q:"Associe chaque type de question à son exemple.",p:[["Question ouverte","« Selon vous, quels sont les principaux modes de transmission du VIH ? »"],["Question fermée","« Êtes-vous d'accord avec l'affirmation suivante ? Oui ou non »"]],e:"OEQ : réponse libre. CEQ : réponses proposées."},
{t:"vf",q:"Une même variable, comme le tabagisme, peut être mesurée par une question nominale, ordinale ou d'intervalle.",a:true,e:"« 100 cigarettes dans votre vie ? », « tous les jours, certains jours, pas du tout ? », « combien par jour ? »"},
{t:"qcm",q:"En général, quelle échelle de réponse utilise-t-on dans les enquêtes téléphoniques ?",o:["4 ou 5 points","10 points","2 points seulement","100 points"],a:0,e:"À quelques exceptions notables près."},
{t:"ordre",q:"Remets dans l'ordre l'échelle de Likert de l'exemple 2.",items:["Tout à fait d'accord","Plutôt d'accord","Ni d'accord ni en désaccord","Plutôt en désaccord","Pas du tout d'accord"],e:"Une échelle ordinale à 5 points."}]},
{id:"u10l3",title:"Fiabilité et biais",q:[
{t:"assoc",q:"Associe chaque fiabilité à sa définition.",p:[["Test-retest","cohérence des réponses à une même question à différents moments"],["Cohérence interne","cohérence entre questions qui évaluent un même concept"]],e:"La fiabilité = stabilité et équivalence des mesures d'un même concept."},
{t:"assoc",q:"Associe chaque biais de questionnaire à sa définition.",p:[["Effet « oui » (acquiescement)","tendance à être d'accord quand on ne sait pas quoi répondre"],["Désirabilité sociale","donner les réponses perçues comme socialement souhaitables"],["Effet de contexte ou d'ordre","réponse influencée par les questions précédentes"]],e:"Le biais d'ancrage est un autre nom de l'effet de contexte."},
{t:"qcm",q:"On demande « combien de rendez-vous galants le mois dernier ? » puis « êtes-vous satisfait de votre vie personnelle ? ». Quel biais illustre l'exemple ?",o:["L'effet de contexte ou d'ordre","La désirabilité sociale","L'acquiescement","La vérité illusoire"],a:0,e:"La première question influence la seconde ; et si on inversait l'ordre ?"},
{t:"qcm",q:"Pourquoi construire des échelles à plusieurs items selon McIver & Carmines (1981) ?",o:["Un seul item représente rarement un concept complexe, et on peut rarement estimer ses propriétés de mesure","Pour allonger le questionnaire","Parce que la loi l'impose","Pour réduire le coût"],a:0,e:"Les mesures à item unique sont moins valides, précises et fiables, et surtout impossibles à évaluer."},
{t:"qcm",q:"Que mesure l'alpha de Cronbach ?",o:["La fiabilité par cohérence interne d'une échelle à plusieurs items","La fiabilité test-retest","La validité prédictive","La taille de l'échantillon"],a:0,e:"Il estime dans quelle mesure les items mesurent le même concept latent."},
{t:"assoc",q:"Associe chaque valeur d'alpha à son interprétation.",p:[["0,65","questionnable"],["0,75","acceptable"],["0,85","bon"],["0,92","excellent"]],e:"< 0,60 faible ; > 0,95 items potentiellement redondants."},
{t:"vf",q:"Un alpha de Cronbach de 0,97 est forcément idéal.",a:false,e:"Au-delà de 0,95, les items sont potentiellement redondants."},
{t:"trou",q:"Un alpha inférieur à 0,60 indique une fiabilité ___.",o:["faible","excellente","acceptable","redondante"],a:0,e:"0,60-0,69 questionnable, 0,70-0,79 acceptable, 0,80-0,89 bon, 0,90-0,95 excellent."}]},
{id:"u10l4",title:"Soutien social et devoir",q:[
{t:"assoc",q:"Associe chaque soutien à son exemple.",p:[["Soutien émotionnel","discuter d'un problème, encourager"],["Soutien instrumental","garder les enfants, prêter de l'argent, transporter"]],e:"Deux (parfois trois) grandes catégories de soutien social."},
{t:"qcm",q:"« Si j'avais besoin d'un prêt d'urgence de 20 dollars, il y a quelqu'un à qui je pourrais m'adresser. » Ce type d'item mesure surtout…",o:["le soutien instrumental","le soutien émotionnel","la désirabilité sociale","la vulnérabilité perçue"],a:0,e:"Aide concrète : argent, transport, logement."},
{t:"qcm",q:"Quelle échelle, développée pour mesurer le soutien social, comprend environ 30 items ?",o:["L'ISEL","L'IPQ","Le HBM","Le COM-B"],a:0,e:"L'échelle internationale d'évaluation du soutien social."},
{t:"vf",q:"Certains items de l'ISEL sont formulés négativement, par exemple « Je n'ai personne à qui parler de mes problèmes intimes ».",a:true,e:"Les items inversés limitent l'effet « oui »."},
{t:"qcm",q:"Selon la méthode de travail, que faire si plusieurs échelles validées existent pour un concept ?",o:["Choisir l'échelle la plus pertinente pour son questionnaire","Les utiliser toutes","Créer sa propre échelle","Poser une seule question"],a:0,e:"Concept simple → au moins une question. Pas d'échelle → élaborer et valider la sienne. Une seule → l'utiliser."},
{t:"qcm",q:"Pour un concept simple, non multifacette, la méthode conseille…",o:["de formuler au moins une question qui le cerne","de chercher une échelle de 30 items","de calculer un alpha","de ne pas le mesurer"],a:0,e:"Les échelles multi-items sont pour les concepts complexes, comme la santé."},
{t:"qcm",q:"Lequel de ces éléments N'EST PAS demandé dans le devoir 1 ?",o:["Les résultats statistiques de l'enquête","Les définitions des concepts","Les noms et références des échelles","Les questions sur la variable dépendante"],a:0,e:"Aussi : questions sur la variable explicative proximale et sur la variable explicative distale."},
{t:"qcm",q:"Dans le sujet « l'âge et la vulnérabilité perçue ont-ils une incidence sur la vaccination antigrippale ? », la variable dépendante est…",o:["la vaccination contre la grippe","l'âge","la vulnérabilité perçue","les personnes âgées"],a:0,e:"L'âge et la vulnérabilité perçue sont les variables explicatives : dans chaque sujet proposé, une variable sociodémographique et une variable psychologique."}]}
]},
/* ================= RAUDE : MODÈLES ================= */
{id:"u11",n:11,c:"--u11",title:"Modèles et décision face au risque",who:"Jocelyn Raude · modèles motivationnels",lessons:[
{id:"u11l1",title:"Qu'est-ce qu'un modèle ?",q:[
{t:"qcm",q:"Un modèle désigne…",o:["une conception formelle faite de propositions ou d'hypothèses simplificatrices pour expliquer ou comprendre un phénomène","une copie exacte de la réalité","une règle juridique","une enquête de terrain"],a:0,e:"Il propose des schémas d'intelligibilité qui rompent avec les prénotions."},
{t:"assoc",q:"Associe chaque critère de Bandura (2002) à sa définition.",p:[["Prédictive","permettre des prévisions sur l'apparition des phénomènes"],["Explicative","préciser les mécanismes et déterminants"],["Efficace","permettre d'intervenir pour changer les comportements"]],e:"Trois critères pour juger la valeur d'une théorie."},
{t:"qcm",q:"« There is nothing more practical than a good theory. » Qui l'a dit ?",o:["Kurt Lewin (1952)","Greenwald (1984)","Albert Einstein","Daniel Bernoulli"],a:0,e:"Greenwald et al. (1984) mettent en garde : la théorie freine la recherche quand on y croit plus qu'aux procédures qui la testent."},
{t:"vf",q:"Dans la littérature, modèle et théorie sont souvent utilisés de manière interchangeable.",a:true,e:"Sinon : modèle = construction spécifique ou ad hoc ; théorie = construction généraliste."},
{t:"assoc",q:"Associe chaque type de modèle à sa visée.",p:[["Synchronique","quelle combinaison de variables explique un comportement à un moment donné"],["Diachronique","quelle séquence idéal-typique mène à adopter un comportement"]],e:"Exemple de modèle diachronique : la carrière déviante. Le TTM est une théorie séquentielle."},
{t:"qcm",q:"Les modèles cognitivistes mettent l'accent sur les facteurs…",o:["intra-individuels de la motivation","inter-individuels","économiques","biologiques"],a:0,e:"Les modèles interactionnistes, sur les facteurs inter-individuels (sociaux)."},
{t:"assoc",q:"Associe chaque motivation à sa source.",p:[["Motivation intrinsèque","facteurs endogènes"],["Motivation extrinsèque","facteurs exogènes"]],e:"Deux grands types d'explication causale des actions humaines."}]},
{id:"u11l2",title:"Deux systèmes, trois approches",q:[
{t:"qcm",q:"Depuis l'Antiquité jusqu'aux Lumières, la rationalité humaine réside surtout dans…",o:["la recherche du plaisir et l'évitement des peines","l'obéissance","la peur de la mort","la recherche de la vérité"],a:0,e:"Point de départ des théories de la décision."},
{t:"assoc",q:"Associe chaque système du modèle de Strack & Deutsch (2004) à sa caractéristique.",p:[["Système réflexif","guidé par la décision, représente le futur, demande beaucoup de capacité"],["Système impulsif","guidé par la perception immédiate, ne représente pas le futur, rapide"]],e:"« Je veux perdre du poids » contre « manger le dessert »."},
{t:"assoc",q:"Associe chaque approche théorique à un exemple.",p:[["Instrumentale ou utilitariste","théorie de l'utilité espérée"],["Sociale-cognitive","Health Belief Model"],["Duale","modèle de l'auto-régulation de Leventhal"]],e:"L'approche duale inclut aussi les heuristiques et biais et le modèle « risk as feeling »."},
{t:"qcm",q:"À quelle approche appartiennent le HBM, la théorie de la motivation pour la protection et la TCP ?",o:["Sociale-cognitive","Instrumentale","Duale","Psychanalytique"],a:0,e:"HBM de Rosenstock & Becker, TMP de Rogers, TCP de Fishbein & Ajzen."},
{t:"vf",q:"Selon Kahneman (2002), le raisonnement (système 2) est lent, sériel, contrôlé et demande un effort.",a:true,e:"L'intuition (système 1) est rapide, parallèle, automatique et sans effort."},
{t:"qcm",q:"Dans le schéma de Kahneman, quels processus partagent le même fonctionnement rapide et automatique ?",o:["La perception et l'intuition (système 1)","L'intuition et le raisonnement","Le raisonnement et la perception","Aucun"],a:0,e:"Le raisonnement (système 2) se distingue des deux."}]},
{id:"u11l3",title:"Probabilités et utilité",q:[
{t:"qcm",q:"Quelle question du chevalier de Méré à Blaise Pascal est citée aux origines de l'approche axiomatique ?",o:["Pourquoi chercher un six en quatre lancers est-il plus avantageux que chercher un double six en vingt-quatre lancers ?","Comment soigner la peste ?","Combien vaut un ducat ?","Faut-il croire en Dieu ?"],a:0,e:"La géométrie du hasard naît de questions sur les jeux."},
{t:"qcm",q:"Selon Antoine Arnault (L'art de penser, 1662), la peur d'un mal devrait être proportionnelle…",o:["à la gravité du mal et à la probabilité de l'événement","à la gravité seule","au bruit du tonnerre","à l'âge de la personne"],a:0,e:"Deux éléments que, selon Matty Chiva (1998), les consommateurs ne prennent pas en compte à la fois."},
{t:"vf",q:"Pour William Simpson (1882), les maladies les plus redoutées sont les plus mortelles.",a:false,e:"C'est l'inverse : les plus redoutées sont les moins mortelles ; leur fréquence rend les maladies courantes moins redoutées."},
{t:"qcm",q:"Entre la certitude de gagner 80 € et 85 % de chances de gagner 100 €, que choisit la plupart des gens ?",o:["La certitude de 80 €","Le pari","Ils refusent de choisir","Ils choisissent au hasard"],a:0,e:"Même si le pari rapporte plus en moyenne (85 €), on préfère la certitude (Tversky et Kahneman)."},
{t:"qcm",q:"Selon Bernoulli (1738), la valeur d'un objet dépend…",o:["de l'utilité qu'il procure, qui dépend de la personne qui l'évalue","de ses avantages, les mêmes pour tous","de son prix de marché","de sa rareté"],a:0,e:"1 000 ducats valent plus pour un pauvre que pour un riche."},
{t:"qcm",q:"Quel paradoxe de Nicolas Bernoulli (1713) est cité ?",o:["Le paradoxe de Saint-Pétersbourg","Le paradoxe de Simpson","Le paradoxe de Condorcet","Le paradoxe de Zénon"],a:0,e:"Daniel Bernoulli publie en 1738 son « exposé d'une nouvelle théorie du risque »."},
{t:"ordre",q:"Remets dans l'ordre le modèle dominant de la décision depuis les années 50 (Loewenstein et al., 2001).",items:["Conséquences anticipées et probabilités subjectives","Évaluation cognitive","Décision","Conséquences"],e:"L'évaluation cognitive combine conséquences et probabilités en utilité espérée."},
{t:"trou",q:"Dans le modèle dominant, l'évaluation cognitive calcule l'utilité ___.",o:["espérée","perçue","marginale","sociale"],a:0,e:"Utilité espérée = conséquences pondérées par les probabilités subjectives."}]}
]},
{id:"u12",n:12,c:"--u12",title:"HBM et motivation pour la protection",who:"Jocelyn Raude · modèles psychologiques",lessons:[
{id:"u12l1",title:"Le Health Belief Model",q:[
{t:"qcm",q:"Pourquoi le HBM a-t-il été développé dans les années 50 ?",o:["Pour comprendre les échecs répétés des campagnes de prévention et de dépistage des maladies infectieuses","Pour mesurer la dépression","Pour organiser le secteur","Pour lutter contre la désinformation"],a:0,e:"Socio-psychologues de l'U.S. Public Health Service (Hochbaum, 1958)."},
{t:"qcm",q:"Quel échec est à l'origine des travaux du HBM en 1952 ?",o:["Un programme gratuit de dépistage de la tuberculose par radiographie mobile","Une campagne antitabac","Un vaccin contre la grippe","Un programme de sevrage alcoolique"],a:0,e:"Des unités mobiles à la sortie des usines et des supermarchés."},
{t:"assoc",q:"Associe chaque composante du HBM à sa définition.",p:[["Susceptibilité perçue","probabilité pour moi d'être touché"],["Gravité perçue","étendue du dommage"],["Barrières perçues","inconvénients de l'action préventive"],["Signaux d'action","ce qui déclenche le passage à l'acte"]],e:"Risque perçu = susceptibilité + gravité ; action = bénéfices − barrières."},
{t:"assoc",q:"Probabilité ou susceptibilité ?",p:[["« Quel pourcentage des Français aura la grippe cette année ? »","probabilité (magnitude)"],["« Quelle est la probabilité que vous ayez la grippe cette année ? »","susceptibilité (vulnérabilité)"]],e:"La susceptibilité concerne un individu donné ; la probabilité, une proportion de la population."},
{t:"vf",q:"Probabilité et susceptibilité sont deux notions identiques dans le HBM.",a:false,e:"Souvent confondues dans la littérature, mais à distinguer clairement."},
{t:"qcm",q:"Qui a proposé en 1977 le concept d'auto-efficacité, intégré au HBM ?",o:["Bandura","Rosenstock","Ajzen","Leventhal"],a:0,e:"La conviction qu'on peut exécuter avec succès le comportement requis."},
{t:"ordre",q:"Selon le cours, pour changer les gens doivent, dans l'ordre…",items:["Se sentir personnellement menacés par leur comportement","Croire que le changement a un coût raisonnable","Se sentir capables de dépasser les barrières"],e:"Menace, coût raisonnable, auto-efficacité."},
{t:"trou",q:"Les signaux d'action (« cues to action ») sont toute information ou circonstance qui favorise le « passage à l'___ ».",o:["acte","écrit","hôpital","échelle"],a:0,e:"Exemple : une campagne, un symptôme, le conseil d'un proche."}]},
{id:"u12l2",title:"Ce que disent les données",q:[
{t:"qcm",q:"Selon la revue de Janz & Becker (1984), quel est le facteur le plus important du HBM ?",o:["Les barrières perçues","La gravité perçue","Les signaux d'action","La susceptibilité seule"],a:0,e:"Dans la plupart des études et pour tous les types de risque."},
{t:"qcm",q:"Selon Janz & Becker (1984), quel facteur est le moins prédictif ?",o:["La gravité perçue","Les barrières perçues","La vulnérabilité","Les bénéfices"],a:0,e:"Même si elle est parfois fortement corrélée à certains comportements à risque."},
{t:"vf",q:"Selon Janz & Becker, la vulnérabilité perçue prédit mieux les comportements que les bénéfices perçus.",a:true,e:"Les deux sont importants, la vulnérabilité sensiblement plus."},
{t:"assoc",q:"Associe chaque perception du risque à sa corrélation avec la vaccination (Brewer et al., 2007).",p:[["Probabilité","r = .26"],["Susceptibilité","r = .24"],["Gravité","r = .16"]],e:"Méta-analyse de 34 études (N = 15 988)."},
{t:"qcm",q:"Que conclut la méta-analyse de Brewer et al. (2007) ?",o:["La perception du risque est un concept fondamental pour prédire les comportements de prévention","La perception du risque ne prédit rien","Seule la gravité compte","La vaccination dépend du revenu"],a:0,e:"La relation est remarquablement stable."},
{t:"qcm",q:"Combien d'études compte la méta-analyse de Brewer et al. (2007) ?",o:["34","65","100","12"],a:0,e:"N = 15 988. Celle de Floyd et al. (2000) sur la PMT en compte 65."}]},
{id:"u12l3",title:"La motivation pour la protection",q:[
{t:"qcm",q:"La théorie de la motivation pour la protection (TMP/PMT) a été développée pour expliquer…",o:["les effets de l'information sur les attitudes et comportements, avec l'accent sur les appels à la peur","la stigmatisation","l'organisation des soins","les biais de questionnaire"],a:0,e:"La motivation pour la protection dépend de l'évaluation de la menace et des moyens d'y faire face."},
{t:"assoc",q:"Range chaque composante de la TMP dans son évaluation.",p:[["Gravité perçue","évaluation de la menace"],["Récompenses intrinsèques","évaluation de la menace"],["Efficacité de la réponse","évaluation du coping"],["Coût de la réponse","évaluation du coping"]],e:"Menace : anticipations, gravité, récompenses intrinsèques et extrinsèques. Coping : efficacité de la réponse, auto-efficacité, coût."},
{t:"qcm",q:"Dans la TMP, les récompenses extrinsèques sont…",o:["l'approbation et le soutien des pairs","le bien-être lié à la cigarette","le prix d'un traitement","les symptômes"],a:0,e:"Les récompenses intrinsèques : le bien-être physique et psychologique associé à la réponse mal-adaptative."},
{t:"qcm",q:"« Arrêter de fumer est efficace pour éviter un cancer. » C'est, dans la TMP…",o:["l'efficacité de la réponse","l'auto-efficacité","la gravité perçue","une récompense extrinsèque"],a:0,e:"L'auto-efficacité serait : « je suis capable d'arrêter »."},
{t:"vf",q:"Pour les promoteurs de la TMP, la peur agit directement sur les changements d'attitude.",a:false,e:"Rôle seulement indirect, via la perception de la gravité (Rogers, 1983)."},
{t:"qcm",q:"Quel effet indésirable une forte peur peut-elle avoir ?",o:["Favoriser le déni ou des postures de défense","Augmenter toujours l'adhésion","Réduire le coût de la réponse","Supprimer les barrières"],a:0,e:"Des comportements mal-adaptatifs."},
{t:"qcm",q:"Selon Floyd et al. (2000), quelle composante de la TMP a le plus fort impact ?",o:["Le coût perçu de la réponse adaptative","La vulnérabilité perçue","La gravité perçue","Les récompenses"],a:0,e:"La vulnérabilité perçue a un impact faible mais significatif ; gravité, récompenses, efficacité et auto-efficacité, un effet modéré."},
{t:"qcm",q:"Combien d'enquêtes la revue de Floyd et al. (2000) rassemble-t-elle ?",o:["65 (N = 30 000)","34 (N = 15 988)","12","200"],a:0,e:"Publiées sur une vingtaine d'années."}]}
]},
{id:"u13",n:13,c:"--u13",title:"TCP, TTM, SRM et COM-B",who:"Jocelyn Raude · modèles et interventions",lessons:[
{id:"u13l1",title:"Comportement planifié et étapes",q:[
{t:"qcm",q:"Sur quels trois concepts repose la théorie du comportement planifié (TCP) d'Ajzen ?",o:["Attitudes, normes subjectives, contrôlabilité perçue","Susceptibilité, gravité, barrières","Capacité, opportunité, motivation","Identité, causes, contrôle"],a:0,e:"Ils déterminent l'intention, qui mène au changement."},
{t:"qcm",q:"Selon Ajzen (1991), les normes subjectives sont…",o:["la perception par la personne de l'approbation ou désapprobation de ses proches significatifs","les lois en vigueur","les valeurs personnelles","la capacité perçue à agir"],a:0,e:"« Whether significant others would approve or disapprove »."},
{t:"qcm",q:"Quelle définition de l'attitude, reprise dans le cours, vient d'Allport (1935) ?",o:["Un état mental et neural de préparation, organisé par l'expérience, qui influence les réponses de l'individu","Un comportement observable","Une norme sociale","Une probabilité subjective"],a:0,e:"Définition classique de la psychologie sociale."},
{t:"ordre",q:"Remets dans l'ordre la chaîne de la TCP.",items:["Attitudes, normes subjectives, contrôlabilité perçue","Intention","Changement de comportement"],e:"L'intention est le pivot du modèle."},
{t:"ordre",q:"Remets dans l'ordre les 5 étapes du modèle transthéorique (TTM).",items:["Pré-contemplation","Contemplation","Préparation","Action","Maintenance"],e:"Une théorie séquentielle (stage theory)."},
{t:"vf",q:"Le modèle transthéorique est une théorie séquentielle.",a:true,e:"Il décrit des étapes que les individus peuvent ou non franchir."},
{t:"trou",q:"Dans la TCP, la ___ perçue est la croyance dans sa capacité à maîtriser son activité et son environnement.",o:["contrôlabilité","gravité","susceptibilité","norme"],a:0,e:"Proche de l'auto-efficacité."}]},
{id:"u13l2",title:"Le modèle d'auto-régulation",q:[
{t:"assoc",q:"Associe chaque dimension de la représentation de la maladie (SRM) à sa question.",p:[["Identité","quels symptômes sont associés à la maladie ?"],["Conséquences","comment ma vie va-t-elle être affectée ?"],["Temporalité","aiguë comme la grippe ou chronique comme le diabète ?"],["Contrôlabilité","peut-on l'éviter ou la soigner ?"]],e:"Cinquième dimension : les causes (comment, pourquoi devient-on malade ?)."},
{t:"qcm",q:"Combien de dimensions compte la représentation cognitive de la maladie dans le SRM ?",o:["5","3","4","8"],a:0,e:"Identité, conséquences, temporalité, causes, contrôlabilité."},
{t:"qcm",q:"Comment Leventhal et al. (1997) appellent-ils le lien entre représentation de la maladie et action ?",o:["Le principe du « si… alors »","Le principe de suffisance","L'effet Werther","La vérité illusoire"],a:0,e:"Principe de symétrie entre la représentation (causes, contrôle) et l'action."},
{t:"qcm",q:"« SI une maladie cardiaque est génétique, ALORS on ne peut rien y faire. » Quelle action en découle ?",o:["L'inaction","L'exercice physique","Le dépistage","Un régime"],a:0,e:"La symétrie entre représentation et action peut mener à l'inaction."},
{t:"vf",q:"Dans le SRM, les représentations de la maladie sont à la fois cognitives et émotionnelles.",a:true,e:"Le schéma de Leventhal suit deux voies parallèles : représentation cognitive et réaction émotionnelle, chacune avec ses stratégies d'adaptation et son évaluation."},
{t:"qcm",q:"Selon Marteau & Weinman (2006), chez qui un test ADN de cancer génétique change-t-il le plus les comportements ?",o:["Chez ceux qui ne voient que les gènes comme cause","Chez ceux qui citent aussi le tabac, l'alimentation ou le stress","Chez tout le monde de la même façon","Chez personne"],a:0,e:"Une information compatible avec les croyances causales préexistantes est mieux assimilée."},
{t:"qcm",q:"Quel questionnaire mesure la perception de la maladie ?",o:["L'IPQ","L'ISEL","L'alpha de Cronbach","Le COM-B"],a:0,e:"Illness Perception Questionnaire : identité (symptômes), causes, autres aspects."},
{t:"vf",q:"On sait aujourd'hui précisément comment modifier les représentations de la maladie d'une population.",a:false,e:"On en sait encore peu ; les moyens font l'objet de nombreuses spéculations."}]},
{id:"u13l3",title:"COM-B et interventions",q:[
{t:"qcm",q:"Selon le COM-B, l'adoption d'un comportement favorable à la santé résulte de…",o:["la capacité, l'opportunité et la motivation à agir","la susceptibilité et la gravité","l'attitude et la norme","l'identité et les causes"],a:0,e:"West, Michie et al. (2020), appliqué au SARS-CoV-2."},
{t:"assoc",q:"Associe chaque composante du COM-B à sa définition.",p:[["Capacité","capacité psychologique et physique à s'engager dans une activité"],["Opportunité","tous les facteurs qui rendent possible la réalisation des intentions"],["Motivation","réflexive (évaluer, planifier) et automatique (émotions, impulsions)"]],e:"Un modèle conçu pour l'intervention."},
{t:"vf",q:"Dans le COM-B, la motivation se divise en motivation réflexive et motivation automatique.",a:true,e:"Réflexive : évaluation prospective et planification. Automatique : émotions et impulsions."},
{t:"qcm",q:"Selon le schéma des mécanismes d'action, une intervention agit sur le comportement…",o:["via un mécanisme d'action : accroître les capacités, les opportunités ou les motivations","directement, sans intermédiaire","seulement par la loi","seulement par la peur"],a:0,e:"Intervention → mécanisme d'action → comportement."},
{t:"ordre",q:"Range l'échelle d'intervention du Nuffield Council (2007), de la plus libre à la plus contraignante.",items:["Ne rien faire","Informer","Former, guider, recommander","Créer une architecture de choix","Inciter positivement","Inciter négativement","Limiter","Interdire"],e:"L'échelle va de la liberté à la contrainte."},
{t:"qcm",q:"Sur l'échelle du Nuffield Council, « créer une architecture de choix » se situe…",o:["entre « former, guider » et « inciter positivement »","tout en haut, près de l'interdiction","tout en bas","au même niveau qu'interdire"],a:0,e:"C'est la place des nudges : plus contraignant qu'informer, moins qu'inciter."},
{t:"qcm",q:"Que propose la taxonomie des BCT présentée en cours ?",o:["Une classification des techniques de changement de comportement (éducation, persuasion, incitation…)","Une liste de médicaments","Une classification des troubles psychiques","Une échelle de soutien social"],a:0,e:"Exemple : « information about health consequences », dans la catégorie éducation."},
{t:"qcm",q:"La citation finale du cours sur la théorie et la pratique est attribuée à…",o:["Albert Einstein","Kurt Lewin","Albert Bandura","Daniel Kahneman"],a:0,e:"« … rien ne fonctionne et on ne sait pas pourquoi »."}]}
]}
];
